
```{r}
lm.SO4.av <- lm(SO4 ~ Abs, data=SO4.average)
summary(lm.SO4.av)
```

```{r plot-so4-av, fig.height=4, fig.width=4, message=FALSE, warning=FALSE}
par(mar=c(3,3,0.5,0.5), mgp=c(1.3,0.2,0), tcl=0.2, font.lab=2, lend="square")
with(SO4.average, plot(SO4 ~ Abs, type="n"))
newAbs <- data.frame(Abs=seq(0.1,1.7,0.02))
conf_av <- predict(lm.SO4.av, newAbs, interval = "conf")
pred_av <- predict(lm.SO4.av, newAbs, interval = "pred")
polygon(c(newAbs$Abs,rev(newAbs$Abs)), c(pred_av[,2], rev(pred_av[,3])),
        col="#00008040", border="transparent")
polygon(c(newAbs$Abs,rev(newAbs$Abs)), c(conf_av[,2], rev(conf_av[,3])),
        col="#c0400040", border="transparent")
with(SO4.average, points(SO4 ~ Abs, pch=10, cex=1.2, lwd=2)) ;abline(lm.SO4.av, col=1)
```

```{r}
lm.SO4.in <- lm(SO4 ~ Abs, data=SO4.indiv)
summary(lm.SO4.in)

```

```{r plot-so4-indiv, fig.height=4, fig.width=4, message=FALSE, warning=FALSE}
par(mar=c(3,3,0.5,0.5), mgp=c(1.3,0.2,0), tcl=0.2, font.lab=2, lend="square")
with(SO4.indiv, plot(SO4 ~ Abs, type="n"))
newAbs <- data.frame(Abs=seq(0.1,1.7,0.02))
conf_in <- predict(lm.SO4.av, newAbs, interval = "conf")
pred_in <- predict(lm.SO4.av, newAbs, interval = "pred")
polygon(c(newAbs$Abs,rev(newAbs$Abs)), c(pred_in[,2], rev(pred_in[,3])),
        col="#00008040", border="transparent")
polygon(c(newAbs$Abs,rev(newAbs$Abs)), c(conf_in[,2], rev(conf_in[,3])),
        col="#90700040", border="transparent")
with(SO4.indiv, points(SO4 ~ Abs, pch=3, lwd=2)) ;abline(lm.SO4.av, col=1)
```
