<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Andrew Rate" />

<meta name="date" content="2024-07-12" />

<title>Multivariate methods - LDA</title>

<script src="site_libs/header-attrs-2.17/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/sandstone.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/tabwid-1.1.0/tabwid.css" rel="stylesheet" />
<link href="site_libs/tabwid-1.1.0/scrool.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #ffffff;
    color: #a0a0a0;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
div.sourceCode
  { color: #1f1c1b; background-color: #ffffff; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span { color: #1f1c1b; } /* Normal */
code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
code span.an { color: #ca60ca; } /* Annotation */
code span.at { color: #0057ae; } /* Attribute */
code span.bn { color: #b08000; } /* BaseN */
code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #924c9d; } /* Char */
code span.cn { color: #aa5500; } /* Constant */
code span.co { color: #898887; } /* Comment */
code span.cv { color: #0095ff; } /* CommentVar */
code span.do { color: #607880; } /* Documentation */
code span.dt { color: #0057ae; } /* DataType */
code span.dv { color: #b08000; } /* DecVal */
code span.er { color: #bf0303; text-decoration: underline; } /* Error */
code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
code span.fl { color: #b08000; } /* Float */
code span.fu { color: #644a9b; } /* Function */
code span.im { color: #ff5500; } /* Import */
code span.in { color: #b08000; } /* Information */
code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
code span.op { color: #1f1c1b; } /* Operator */
code span.ot { color: #006e28; } /* Other */
code span.pp { color: #006e28; } /* Preprocessor */
code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #ff5500; } /* SpecialString */
code span.st { color: #bf0303; } /* String */
code span.va { color: #0057ae; } /* Variable */
code span.vs { color: #bf0303; } /* VerbatimString */
code span.wa { color: #bf0303; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Sessions</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="about.html">For beginners</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Intro

    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro.html">Intro</a>
    </li>
    <li>
      <a href="intro-GG.html">Intro+ggplot</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Plots

    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="plots.html">Plots-baseR</a>
    </li>
    <li>
      <a href="plots-GG.html">Plots-ggplot</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Compare

    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="means.html">Compare means (parametric)</a>
    </li>
    <li>
      <a href="nonparam.html">Non-parametric comparisons</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Relate

    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="correl.html">Correlation</a>
    </li>
    <li>
      <a href="regression.html">Simple linear regression</a>
    </li>
    <li>
      <a href="reg-group.html">Grouped linear regression</a>
    </li>
    <li>
      <a href="reg-multi.html">Multiple linear regression</a>
    </li>
    <li>
      <a href="timeseries.html">Time series analysis</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Maps

    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="maps.html">Map data with tile backgrounds</a>
    </li>
    <li>
      <a href="spatial.html">Spatial statistics</a>
    </li>
    <li>
      <a href="spat-interp.html">Spatial interpolation</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Multi

    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="pca.html">Principal components analysis</a>
    </li>
    <li>
      <a href="vegan.html">Analysis of species presence-absence data</a>
    </li>
    <li>
      <a href="lda.html">Linear discriminant analysis</a>
    </li>
    <li>
      <a href="cluster.html">Cluster analysis</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Util

    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="tables.html">Tables &amp; trigger value counts</a>
    </li>
    <li>
      <a href="distributions.html">Distribution checking</a>
    </li>
    <li>
      <a href="residuals.html">Regression residuals to identify contamination</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://www.uwa.edu.au/schools/agriculture-and-environment">UWA School of Agriculture and Environment</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->
<!DOCTYPE html>

<html>
<body>
<h3><img src="./images/2015-UWA-Full-Hor-CMYK.png" alt="UWA logo" align="right"><span style="color:#003087;">Material to support teaching in Environmental Science<br />at The University of Western Australia</span></h3>
<h4><span style="color:#93721A;">Units ENVT3361, ENVT4461, and ENVT5503</span></h4></p>
</body>
</html>

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Multivariate methods - LDA</h1>
<h3 class="subtitle">Linear Discriminant Analysis</h3>
<h4 class="author">Andrew Rate</h4>
<h4 class="date">2024-07-12</h4>

</div>


<style type="text/css">
  body{
  font-size: 12pt;
}
</style>
<p> </p>
<p><strong>Linear Discriminant Analysis (LDA)</strong> is a
<strong>supervised classification</strong> method that uses the
information from multiple variables to separate the observations into
each of the ‘classes’ or categories in a factor variable. LDA is a
<em>supervised</em> classification since it requires us to use
pre-defined categories in our dataset, rather than identifying the
categories itself. The LDA procedure creates functions of the dataset
variables which maximise the separation between the pre-defined
categories. LDA is also sensitive to compositional closure, as I hope
we're starting to expect for multivariate methods by now! Predicting
existing categories is not the most useful application of LDA – ideally,
we would like to measure some key variables so we can predict a
previously unknown category (a strategy for machine learning). Towards
the end of this section we will divide our dataset into two groups – one
to 'train' our LDA model to generate a set of linear discriminant
functions, which we can then apply to the remaining observations in our
dataset to <em>validate</em> our LDA model.</p>
<p>Linear discriminant analysis resembles principal components analysis
(PCA), in that it generates new sets of variables (dimensions) to reduce
the complexity (<em>i.e</em>. dimensionality) of multivariate data. Key
differences between LDA and PCA are that:</p>
<ul>
<li>the components of PCA capture successively less multivariate
<em>variance</em> (and are are not 'supervised' by pre-defined
categories)</li>
<li>the dimensions of LDA <em>maximise some measure of separation</em>
between supervised categories.</li>
</ul>
<p>In LDA, this is achieved by generating new variables (the dimensions)
which are linear functions of the existing variables in the dataset.</p>
<p>To implement LDA in R, we use the <code>lda()</code> function in the
<code>MASS</code> package (Venables and Ripley, 2002). We specify the
variables to be considered using a formula similar to that used for
multiple regression, and we set the prior (initial) probabilities of an
observation being in a particular category at the actual frequencies at
which those categories occur in the data.</p>
<p>In practice, we apply LDA to a scaled transformations of our
variables (<em>i.e</em>. conversion to Z-scores with mean = 0 and
standard deviation = 1). This avoids the variables with larger absolute
values having an unbalanced effect on the results.</p>
<p> </p>
<div id="load-packages-and-read-and-transform-data"
class="section level3">
<h3>Load packages, and read and transform data</h3>
<div
style="border: 2px solid #039; background-color:#f0f0f0; padding: 8px;">
<p><strong>Data Source</strong>: We are using a curated version of a
whole rock major element dataset from Hallberg (2006) <a
href="https://catalogue.data.wa.gov.au/dataset/hallberg-geochemistry"
target="_blank">https://catalogue.data.wa.gov.au/dataset/hallberg-geochemistry</a></p>
</div>
<p> </p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(klaR)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">library</span>(viridis)</span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a>git <span class="ot">&lt;-</span> <span class="st">&quot;https://raw.githubusercontent.com/Ratey-AtUWA/Learn-R-web/main/&quot;</span></span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a>Hallberg <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">paste0</span>(git,<span class="st">&quot;HallbergTE.csv&quot;</span>), <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-8"><a href="#cb1-8" tabindex="-1"></a><span class="fu">head</span>(Hallberg[,<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)])</span>
<span id="cb1-9"><a href="#cb1-9" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st">------------------</span><span class="sc">\n</span><span class="st">&quot;</span>)</span>
<span id="cb1-10"><a href="#cb1-10" tabindex="-1"></a>Hallberg_clr <span class="ot">&lt;-</span> Hallberg</span>
<span id="cb1-11"><a href="#cb1-11" tabindex="-1"></a>Hallberg_clr[,<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)] <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">apply</span>(Hallberg[,<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)], <span class="at">MARGIN =</span> <span class="dv">1</span>,</span>
<span id="cb1-12"><a href="#cb1-12" tabindex="-1"></a>                           <span class="at">FUN =</span> <span class="cf">function</span>(x){<span class="fu">log</span>(x) <span class="sc">-</span> <span class="fu">mean</span>(<span class="fu">log</span>(x))}))</span>
<span id="cb1-13"><a href="#cb1-13" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(<span class="fu">head</span>(Hallberg_clr[,<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)]),<span class="dv">2</span>))</span></code></pre></div>
<pre><code>##     SiO2  TiO2  Al2O3 Fe2O3   FeO  MnO   MgO    CaO  Na2O  K2O P2O5 Co  Cr  Cu  Ni Rb  Sr   V  Y  Zn Zr
## 1 518000  9500 147000 17000 89000 2000 46000 126000 22000 2300 1600 60 375 134 154  1  96 299 22  95 61
## 2 493000  7900 153000  7000 98000 2200 90000 103000 26000 1300 1500 59 395  72 172  4 112 313 17  99 50
## 3 498000 12300 164000 14000 94000 1800 62000 101000 29000 3900 1600 63 130 116  87 27 112 399 26 102 65
## 4 531000  7400 123000 17000 72000 2200 74000 124000 30000 1200 1100 70 332  33 110  3  60 304 14 100 45
## 5 503000 10400 163000  8000 91000 2500 47000 123000 26000 1900 1600 61 470 110 173  7 124 306 26 105 65
## 6 521000  6000 150000 14000 79000 1700 78000  83000 35200 4600  800 47 192 152 120  3  79 310 31  75 38
##
## ------------------
##   SiO2 TiO2 Al2O3 Fe2O3  FeO  MnO  MgO  CaO Na2O   K2O  P2O5    Co    Cr    Cu    Ni    Rb    Sr     V     Y    Zn
## 1 5.89 1.90  4.63  2.48 4.13 0.34 3.47 4.48 2.74  0.48  0.11 -3.17 -1.34 -2.37 -2.23 -7.26 -2.70 -1.56 -4.17 -2.71
## 2 5.85 1.72  4.68  1.60 4.24 0.44 4.15 4.29 2.91 -0.08  0.06 -3.18 -1.28 -2.98 -2.11 -5.87 -2.54 -1.51 -4.42 -2.66
## 3 5.70 2.00  4.59  2.13 4.03 0.08 3.62 4.10 2.86  0.85 -0.04 -3.28 -2.55 -2.67 -2.95 -4.12 -2.70 -1.43 -4.16 -2.79
## 4 6.04 1.77  4.58  2.60 4.04 0.55 4.07 4.59 3.17 -0.05 -0.14 -2.89 -1.34 -3.65 -2.44 -6.04 -3.05 -1.43 -4.50 -2.54
## 5 5.75 1.87  4.63  1.61 4.04 0.45 3.38 4.34 2.79  0.17  0.00 -3.26 -1.22 -2.67 -2.22 -5.43 -2.55 -1.65 -4.12 -2.72
## 6 5.94 1.47  4.69  2.32 4.05 0.21 4.04 4.10 3.24  1.21 -0.54 -3.38 -1.97 -2.20 -2.44 -6.13 -2.86 -1.49 -3.79 -2.91
##      Zr
## 1 -3.15
## 2 -3.34
## 3 -3.24
## 4 -3.34
## 5 -3.20
## 6 -3.59</code></pre>
<p> </p>
</div>
<div id="lda-on-closed-whole-rock-major-element-data"
class="section level2">
<h2>LDA on closed whole rock major element data</h2>
<p>We will use LDA to discriminate the rock type, contained in the
column <code>Rock</code> in the Hallberg dataset. The variables we will
use are the trace element contents, Co, Cr, Cu, Ni, Rb, Sr, V, Y, Zn,
and Zr, and the minor element Ti (as TiO<sub>2</sub>). We choose these
elements as there is reason to believe that some of these elements can
discriminate rocks at the mafic end of the rock classification spectrum
(which includes the rocks in this dataset, all being ‘greenstones’).</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a>data0 <span class="ot">&lt;-</span> Hallberg</span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a>data0[,<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)] <span class="ot">&lt;-</span> <span class="fu">scale</span>(data0[,<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)]) <span class="co"># scale just numeric variables</span></span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a>lda_rock_clos <span class="ot">&lt;-</span> <span class="fu">lda</span>(<span class="at">formula =</span> Rock <span class="sc">~</span> SiO2 <span class="sc">+</span> TiO2 <span class="sc">+</span> Al2O3 <span class="sc">+</span> Fe2O3 <span class="sc">+</span> FeO <span class="sc">+</span> MnO <span class="sc">+</span> </span>
<span id="cb3-4"><a href="#cb3-4" tabindex="-1"></a>                               MgO <span class="sc">+</span> CaO <span class="sc">+</span> Na2O <span class="sc">+</span> K2O <span class="sc">+</span> P2O5 <span class="sc">+</span> Co <span class="sc">+</span> Cr <span class="sc">+</span> Cu <span class="sc">+</span> </span>
<span id="cb3-5"><a href="#cb3-5" tabindex="-1"></a>                               Ni <span class="sc">+</span> Rb <span class="sc">+</span> Sr <span class="sc">+</span> TiO2 <span class="sc">+</span> V <span class="sc">+</span> Y <span class="sc">+</span> Zn <span class="sc">+</span> Zr, </span>
<span id="cb3-6"><a href="#cb3-6" tabindex="-1"></a>                    <span class="at">data =</span> data0,</span>
<span id="cb3-7"><a href="#cb3-7" tabindex="-1"></a>                    <span class="at">prior =</span> <span class="fu">as.numeric</span>(<span class="fu">summary</span>(Hallberg<span class="sc">$</span>Rock))<span class="sc">/</span><span class="fu">nrow</span>(Hallberg)) </span>
<span id="cb3-8"><a href="#cb3-8" tabindex="-1"></a><span class="fu">print</span>(lda_rock_clos)</span></code></pre></div>
<pre><code>## Call:
## lda(Rock ~ SiO2 + TiO2 + Al2O3 + Fe2O3 + FeO + MnO + MgO + CaO +
##     Na2O + K2O + P2O5 + Co + Cr + Cu + Ni + Rb + Sr + TiO2 +
##     V + Y + Zn + Zr, data = data0, prior = as.numeric(summary(Hallberg$Rock))/nrow(Hallberg))
##
## Prior probabilities of groups:
##            Basalt          Dolerite            Gabbro    High-Mg Basalt        Peridotite Spinel Peridotite
##       0.572237960       0.082152975       0.019830028       0.243626062       0.073654391       0.008498584
##
## Group means:
##                          SiO2       TiO2      Al2O3       Fe2O3         FeO         MnO        MgO        CaO
## Basalt             0.31715964  0.3639023  0.5185686  0.11684431 -0.05196006  0.15207936 -0.4873181  0.3845373
## Dolerite           0.07094283  0.5086812  0.5001386 -0.37013107  0.51782685  0.08790125 -0.3528093  0.2754014
## Gabbro            -0.21226217  0.8653722  0.9048671 -0.45957552  0.75684625  0.50338818 -0.5250988  0.2659761
## High-Mg Basalt    -0.06092571 -0.5557138 -0.6285513  0.06471332  0.01407866 -0.07073728  0.3975844 -0.1757412
## Peridotite        -2.14584110 -1.6300027 -2.4938180 -0.48667218 -0.44373947 -1.07694424  2.7040310 -2.5588057
## Spinel Peridotite -1.20209141 -1.3820589 -2.2314196 -0.85452986  0.16916358 -0.90297610  2.6161166 -1.9607692
##                         Na2O         K2O       P2O5         Co         Cr          Cu         Ni            Rb
## Basalt             0.4071412  0.08552056  0.3527230 -0.4022658 -0.5066490  0.09548292 -0.3980978  0.0004046366
## Dolerite           0.1974804  0.04056308  0.7279872 -0.4048893 -0.4987395  0.44460365 -0.3926526  0.1560216669
## Gabbro             0.5429423  0.07881283  0.9400805 -0.5775627 -0.6027127  0.46759340 -0.4427489  0.1917871862
## High-Mg Basalt    -0.4829015  0.06215950 -0.6758532  0.4610102  0.8619559 -0.33078224  0.1577551  0.0821465878
## Peridotite        -1.7416849 -0.83083094 -1.4067190  1.9182234  1.5911966 -0.24584612  2.8097518 -0.4392366274
## Spinel Peridotite -1.6522397 -0.91576127 -1.4147188  2.5072446  1.8420722 -0.20497954  2.7604777 -0.5311098263
##                            Sr          V          Y          Zn         Zr
## Basalt             0.26202264  0.4100487  0.2553190 -0.19118546  0.2764816
## Dolerite           0.01128675  0.5267777  0.3043583 -0.06376382  0.1747826
## Gabbro            -0.09755553  0.7842967  0.2854792  0.26707365  0.1582256
## High-Mg Basalt    -0.25712595 -0.5206124 -0.3199898  0.34516149 -0.2851220
## Peridotite        -1.05311422 -2.0632007 -1.2243902  0.30013690 -1.2959201
## Spinel Peridotite -1.02639968 -1.7268598 -1.0153084  0.37055020 -1.2703848
##
## Coefficients of linear discriminants:
##                LD1         LD2         LD3          LD4         LD5
## SiO2  -0.515714496  0.33956357  0.73483678 -1.275875748  0.07446471
## TiO2  -0.095212690 -0.49960455 -0.22205308 -0.461132185 -0.90056720
## Al2O3 -0.718850396 -1.46870680  0.45244936 -0.765817667 -1.64246879
## Fe2O3 -0.198520002  0.22445255  0.64397989 -0.148943627 -0.09299670
## FeO   -0.381206411  0.10147817 -0.29005099 -0.604149508  0.17405411
## MnO    0.146397067  0.01148665  0.32790459  0.224716717 -0.31529801
## MgO    0.681879245 -0.57465144  0.54566500 -1.792504911  0.08876294
## CaO   -0.572122094  0.28557494  0.59162313 -0.815308162  0.36523048
## Na2O  -0.053136781  0.12731744  0.54881490  0.003944571 -0.10845946
## K2O   -0.004923677  0.20959370 -0.12497351 -0.126661119 -0.21270710
## P2O5  -0.220628145 -0.47959337 -0.40701599 -0.099034011  0.23377074
## Co     0.346677694  0.20711583 -0.02834412 -0.419386489 -0.01150618
## Cr    -0.494258627  1.35293562 -0.03545759 -0.001876091 -0.76123618
## Cu    -0.095446935  0.13260580 -0.28562945  0.170822969  0.39939738
## Ni     0.601844007 -1.73346694  1.53994577 -0.655721720 -0.67375939
## Rb    -0.018503492 -0.03076574 -0.14299599  0.015746299  0.01526565
## Sr     0.077656452 -0.10232694  0.29369466  0.105615697  0.09131547
## V      0.028646629  0.18491046  0.38220837 -0.133033425  0.40344207
## Y     -0.049032227  0.04236829 -0.21394852 -0.203492141  0.08223319
## Zn    -0.130404312  0.13998531 -0.08672013  0.330717988 -0.32195927
## Zr     0.153648832  0.27883508  0.23748549  0.444240032  0.51596379
##
## Proportion of trace:
##    LD1    LD2    LD3    LD4    LD5
## 0.8047 0.1716 0.0160 0.0057 0.0021</code></pre>
<p> </p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a>cormat <span class="ot">&lt;-</span> <span class="fu">rcorr.adjust</span>(data0[,<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)], </span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a>                       <span class="at">type=</span><span class="st">&quot;pearson&quot;</span>)</span>
<span id="cb5-3"><a href="#cb5-3" tabindex="-1"></a>cmx <span class="ot">&lt;-</span> <span class="fu">round</span>(cormat<span class="sc">$</span>R<span class="sc">$</span>r,<span class="dv">3</span>) ; cmx[<span class="fu">which</span>(cmx<span class="sc">&gt;</span><span class="fl">0.9999</span>)] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb5-4"><a href="#cb5-4" tabindex="-1"></a><span class="fu">corrplot</span>(cmx, <span class="at">method=</span><span class="st">&quot;ellipse&quot;</span>, <span class="at">type=</span><span class="st">&quot;upper&quot;</span>, <span class="at">tl.col=</span><span class="dv">1</span>, <span class="at">tl.cex=</span><span class="fl">1.4</span>, </span>
<span id="cb5-5"><a href="#cb5-5" tabindex="-1"></a>                   <span class="at">cl.cex=</span><span class="fl">1.4</span>, <span class="at">na.label =</span> <span class="st">&quot; &quot;</span>, <span class="at">tl.pos=</span><span class="st">&quot;lt&quot;</span>)</span>
<span id="cb5-6"><a href="#cb5-6" tabindex="-1"></a><span class="fu">corrplot</span>(cmx, <span class="at">method=</span><span class="st">&quot;color&quot;</span>, <span class="at">type=</span><span class="st">&quot;lower&quot;</span>, <span class="at">tl.col=</span><span class="dv">1</span>, <span class="at">addCoef.col=</span><span class="dv">1</span>, </span>
<span id="cb5-7"><a href="#cb5-7" tabindex="-1"></a>         <span class="at">addgrid.col =</span> <span class="st">&quot;grey&quot;</span>, <span class="at">na.label =</span> <span class="st">&quot; &quot;</span>, <span class="at">cl.pos=</span><span class="st">&quot;n&quot;</span>, <span class="at">tl.pos=</span><span class="st">&quot;n&quot;</span>, <span class="at">add=</span><span class="cn">TRUE</span>,</span>
<span id="cb5-8"><a href="#cb5-8" tabindex="-1"></a>         <span class="at">col=</span><span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">&quot;#ffe0e0&quot;</span>,<span class="st">&quot;white&quot;</span>,<span class="st">&quot;#e0e0ff&quot;</span>))(<span class="dv">200</span>))</span></code></pre></div>
<div class="figure">
<img src="lda_files/figure-html/Fig1-correl-matrix-closed-1.png" alt="Figure 1: Correlation matrix for closed-set predictors (not part of LDA output)&gt;" width="80%" />
<p class="caption">
Figure 1: Correlation matrix for closed-set predictors (not part of LDA
output)&gt;
</p>
</div>
<p> </p>
</div>
<div id="lda-on-open-clr-whole-rock-major-element-data"
class="section level2">
<h2>LDA on open (CLR) whole rock major element data</h2>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a>data0 <span class="ot">&lt;-</span> Hallberg_clr</span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>data0[,<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)] <span class="ot">&lt;-</span> <span class="fu">scale</span>(data0[,<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)]) <span class="co"># scale just numeric variables</span></span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>lda_rock_open <span class="ot">&lt;-</span> <span class="fu">lda</span>(<span class="at">formula =</span> Rock <span class="sc">~</span> SiO2 <span class="sc">+</span> TiO2 <span class="sc">+</span> Al2O3 <span class="sc">+</span> Fe2O3 <span class="sc">+</span> FeO <span class="sc">+</span> MnO <span class="sc">+</span> </span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a>                               MgO <span class="sc">+</span> CaO <span class="sc">+</span> Na2O <span class="sc">+</span> K2O <span class="sc">+</span> P2O5 <span class="sc">+</span> Co <span class="sc">+</span> Cr <span class="sc">+</span> Cu <span class="sc">+</span> </span>
<span id="cb6-5"><a href="#cb6-5" tabindex="-1"></a>                               Ni <span class="sc">+</span> Rb <span class="sc">+</span> Sr <span class="sc">+</span> TiO2 <span class="sc">+</span> V <span class="sc">+</span> Y <span class="sc">+</span> Zn <span class="sc">+</span> Zr, </span>
<span id="cb6-6"><a href="#cb6-6" tabindex="-1"></a>                    <span class="at">data =</span> data0,</span>
<span id="cb6-7"><a href="#cb6-7" tabindex="-1"></a>                    <span class="at">prior =</span> <span class="fu">as.numeric</span>(<span class="fu">summary</span>(data0<span class="sc">$</span>Rock))<span class="sc">/</span><span class="fu">nrow</span>(data0)) </span>
<span id="cb6-8"><a href="#cb6-8" tabindex="-1"></a><span class="fu">print</span>(lda_rock_open)</span></code></pre></div>
<pre><code>## Call:
## lda(Rock ~ SiO2 + TiO2 + Al2O3 + Fe2O3 + FeO + MnO + MgO + CaO +
##     Na2O + K2O + P2O5 + Co + Cr + Cu + Ni + Rb + Sr + TiO2 +
##     V + Y + Zn + Zr, data = data0, prior = as.numeric(summary(data0$Rock))/nrow(data0))
##
## Prior probabilities of groups:
##            Basalt          Dolerite            Gabbro    High-Mg Basalt        Peridotite Spinel Peridotite
##       0.572237960       0.082152975       0.019830028       0.243626062       0.073654391       0.008498584
##
## Group means:
##                          SiO2       TiO2      Al2O3       Fe2O3         FeO         MnO        MgO         CaO
## Basalt            -0.25738187  0.2537924  0.4391688 -0.05095198 -0.31451236 -0.20473569 -0.4997587  0.22117524
## Dolerite          -0.44744406  0.3995203  0.3124530 -0.65188391 -0.04020638 -0.32690019 -0.3417888  0.06871215
## Gabbro            -0.73856003  0.6268184  0.4980210 -0.77364397 -0.04090888 -0.20827176 -0.6409722 -0.04989445
## High-Mg Basalt     0.04139358 -0.3768292 -0.5781595  0.17599105  0.06554438  0.02869537  0.4862839  0.04587332
## Peridotite         2.40586837 -1.2318624 -1.7532776  0.74104059  2.10239359  1.82020929  2.5760285 -1.83933626
## Spinel Peridotite  1.34150366 -0.9347177 -1.9841498  0.07005191  1.56159769  0.83379111  2.1842575 -0.81438407
##                         Na2O         K2O       P2O5         Co         Cr          Cu         Ni          Rb         Sr
## Basalt             0.4384678  0.21987167  0.4002674 -0.4237590 -0.4987620  0.08412522 -0.4535467 -0.04076464  0.3787489
## Dolerite           0.3278769  0.14481862  0.6579856 -0.4818491 -0.5237427  0.41970263 -0.4723105  0.09066789  0.1653297
## Gabbro             0.4570478  0.29204599  0.8366189 -0.7165812 -0.6691570  0.51172142 -0.6727888  0.16761638  0.0440467
## High-Mg Basalt    -0.3145889  0.02023643 -0.6683486  0.3640927  0.7938929 -0.40704189  0.4003037  0.12161747 -0.4312253
## Peridotite        -2.6333811 -1.79286121 -1.6153835  2.5653261  1.8182359  0.02413714  2.6339247 -0.21734714 -1.5805855
## Spinel Peridotite -1.9185672 -1.92802674 -2.1046561  2.1928540  1.6912115  0.54377178  2.3715978 -0.12543422 -1.1431906
##                            V          Y         Zn         Zr
## Basalt             0.3514809  0.3641648 -0.2255523  0.3536939
## Dolerite           0.4385002  0.3361024 -0.1129799  0.2534661
## Gabbro             0.5247575  0.3886290  0.2333842  0.2550671
## High-Mg Basalt    -0.4946752 -0.4070925  0.1464523 -0.3289291
## Peridotite        -1.5608713 -1.8247550  1.1886606 -1.7881890
## Spinel Peridotite -1.4214092 -1.1916923  1.2347375 -1.9337810
##
## Coefficients of linear discriminants:
##                LD1          LD2         LD3         LD4         LD5
## SiO2   0.311906556  0.475172430  1.06386434 -0.31153403 -0.49360643
## TiO2  -0.035043310  0.151688641 -0.14721971 -0.09186873  0.17887478
## Al2O3 -0.312637279  0.466394555 -0.14735485 -0.30383542  0.40628481
## Fe2O3 -0.022620301 -0.390680981  0.66513139 -0.12737824  0.29133594
## FeO   -0.063901662  0.595404868 -0.15423496 -0.26329116  0.26140339
## MnO    0.232120983  0.273346069  0.18819409 -0.43680365  0.26962349
## MgO    0.531918843 -0.401806131 -2.67147472 -0.18459843 -1.74702057
## CaO   -0.615973836 -0.613615069 -0.28059295  0.48378064 -0.31940725
## Na2O  -0.738743065 -0.498253105  0.21204722  0.80358159 -0.17175823
## K2O    0.021600745 -0.380364118  0.01703155 -0.70089981 -0.31534337
## P2O5  -0.430115909  0.472152464 -0.32302277 -0.33080910 -0.19785901
## Co     0.443719497 -0.291897897 -0.23779641  0.39291494 -0.08560493
## Cr     0.306727775 -1.047240560  0.54144693 -0.76768593  0.46797732
## Cu    -0.059583571  0.149775151 -0.12979112  0.14745878  0.01141351
## Ni     0.147582733  0.824302811  0.87784570  1.62502433  0.18782951
## Rb     0.002277406  0.308139649 -0.09488075  0.13556801  0.26716383
## Sr     0.483922453  0.689810105  0.01330317  0.34114182 -0.15189125
## V      0.023458566  0.001742575  0.06663428  0.07764911 -0.39425633
## Y     -0.028468272  0.031123166 -0.15387790  0.34661178  0.12424677
## Zn    -0.089890850 -0.073273061  0.06237525 -0.05846468  0.53558740
## Zr     0.097653277 -0.197155426 -0.06140115 -0.31397470 -0.61079156
##
## Proportion of trace:
##    LD1    LD2    LD3    LD4    LD5
## 0.8494 0.1247 0.0173 0.0071 0.0015</code></pre>
<p> </p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a>cormat <span class="ot">&lt;-</span> <span class="fu">rcorr.adjust</span>(data0[,<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)], </span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>                       <span class="at">type=</span><span class="st">&quot;pearson&quot;</span>)</span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a>cmx <span class="ot">&lt;-</span> <span class="fu">round</span>(cormat<span class="sc">$</span>R<span class="sc">$</span>r,<span class="dv">3</span>) ; cmx[<span class="fu">which</span>(cmx<span class="sc">&gt;</span><span class="fl">0.9999</span>)] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb8-4"><a href="#cb8-4" tabindex="-1"></a><span class="fu">corrplot</span>(cmx, <span class="at">method=</span><span class="st">&quot;ellipse&quot;</span>, <span class="at">type=</span><span class="st">&quot;upper&quot;</span>, <span class="at">tl.col=</span><span class="dv">1</span>, <span class="at">tl.cex=</span><span class="fl">1.4</span>, </span>
<span id="cb8-5"><a href="#cb8-5" tabindex="-1"></a>                   <span class="at">cl.cex=</span><span class="fl">1.4</span>, <span class="at">na.label =</span> <span class="st">&quot; &quot;</span>, <span class="at">tl.pos=</span><span class="st">&quot;lt&quot;</span>)</span>
<span id="cb8-6"><a href="#cb8-6" tabindex="-1"></a><span class="fu">corrplot</span>(cmx, <span class="at">method=</span><span class="st">&quot;ellipse&quot;</span>, <span class="at">type=</span><span class="st">&quot;lower&quot;</span>, <span class="at">tl.col=</span><span class="dv">1</span>, <span class="at">addCoef.col=</span><span class="dv">1</span>, </span>
<span id="cb8-7"><a href="#cb8-7" tabindex="-1"></a>         <span class="at">addgrid.col =</span> <span class="st">&quot;grey&quot;</span>, <span class="at">na.label =</span> <span class="st">&quot; &quot;</span>, <span class="at">cl.pos=</span><span class="st">&quot;n&quot;</span>, <span class="at">tl.pos=</span><span class="st">&quot;n&quot;</span>, <span class="at">add=</span><span class="cn">TRUE</span>,</span>
<span id="cb8-8"><a href="#cb8-8" tabindex="-1"></a>         <span class="at">col=</span><span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">&quot;#ffe0e0&quot;</span>,<span class="st">&quot;white&quot;</span>,<span class="st">&quot;#e0e0ff&quot;</span>))(<span class="dv">200</span>))</span></code></pre></div>
<div class="figure">
<img src="lda_files/figure-html/Fig2-correl-matrix-CLR-1.png" alt="Figure 2: Correlation matrix for clr-transformed predictors (not part of LDA output)&gt;" width="60%" />
<p class="caption">
Figure 2: Correlation matrix for clr-transformed predictors (not part of
LDA output)&gt;
</p>
</div>
<p> </p>
<p>The LDA model specified and the prior probabilities are reported back
to us in the output. The <em>Group means</em> sub-table in the output
contains the centroids of the categories (5 classes, in our whole rock
data) in the n-dimensional space defined by the n variables used for
classification. The <em>Coefficients of linear</em>
<em>discriminants</em> sub-table essentially defines the linear
discriminant functions that separate our categories, since each function
(LD1, LD2, <em>etc</em>.) is a linear combination of all the variables.
Finally, the <em>Proportion of trace</em> sub-table gives the
<em>proportions of between-class variance</em> that are explained by
successive discriminant functions (<em>e.g</em>. for the open Hallberg
rock data, LD1 explains 0.849 (85%) and LD2 explains 0.125 (12.5%) of
variance between Rock type categories).</p>
<p>[<strong>Note</strong>: sometimes we cannot make an LDA model,
because the predictors are collinear (highly correlated). We may be able
to fix this by inspecting a correlation matrix for all the predictor
variables, and removing <em>one</em> variable at a time from correlated
pairs, then re-running the LDA procedure. By analogy with multiple
linear regression, this would mean a Pearson's r ≥ 0.8.]</p>
<p> </p>
</div>
<div id="visualising-lda-separation" class="section level2">
<h2>Visualising LDA separation</h2>
<div id="lda-histograms" class="section level3">
<h3>LDA histograms</h3>
<p>We can plot the separation achieved by each linear discriminant (LD)
function by predicting the classification using the input data, then
using the <code>ldahist()</code> function (Venables and Ripley 2002). To
see the separation in another LDA dimension, we change the subscript in
the <code>predClos$x[,1]</code> option. Histograms (actually drawn with
custom code, enabling a plot with a side-by side comparison) are shown
in Figure 3.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a>predClos <span class="ot">&lt;-</span> <span class="fu">predict</span>(lda_rock_clos, Hallberg[,<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)])</span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a>predOpen <span class="ot">&lt;-</span> <span class="fu">predict</span>(lda_rock_open, Hallberg[,<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)])</span>
<span id="cb9-3"><a href="#cb9-3" tabindex="-1"></a>LD1c <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Rock=</span><span class="fu">as.character</span>(Hallberg<span class="sc">$</span>Rock),<span class="at">LD1=</span>predClos<span class="sc">$</span>x[,<span class="dv">1</span>])</span>
<span id="cb9-4"><a href="#cb9-4" tabindex="-1"></a>LD1c<span class="sc">$</span>Rock <span class="ot">&lt;-</span> <span class="fu">factor</span>(LD1c<span class="sc">$</span>Rock, <span class="at">levels=</span><span class="fu">levels</span>(Hallberg<span class="sc">$</span>Rock))</span>
<span id="cb9-5"><a href="#cb9-5" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="fu">nlevels</span>(LD1c<span class="sc">$</span>Rock),<span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">oma =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>), </span>
<span id="cb9-6"><a href="#cb9-6" tabindex="-1"></a>    <span class="at">mgp =</span> <span class="fu">c</span>(<span class="fl">0.75</span>,<span class="fl">0.2</span>,<span class="dv">0</span>), <span class="at">tcl=</span><span class="fl">0.15</span>)</span>
<span id="cb9-7"><a href="#cb9-7" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nlevels</span>(LD1c<span class="sc">$</span>Rock)){</span>
<span id="cb9-8"><a href="#cb9-8" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">subset</span>(LD1c, <span class="at">subset=</span>LD1c<span class="sc">$</span>Rock<span class="sc">==</span><span class="fu">levels</span>(LD1c<span class="sc">$</span>Rock)[i]),</span>
<span id="cb9-9"><a href="#cb9-9" tabindex="-1"></a>       <span class="fu">hist</span>(LD1, <span class="at">main =</span> <span class="st">&quot;&quot;</span>, <span class="at">breaks =</span> <span class="fu">pretty</span>(LD1c<span class="sc">$</span>LD1, <span class="at">n=</span><span class="dv">20</span>), <span class="at">col=</span><span class="dv">5</span>,</span>
<span id="cb9-10"><a href="#cb9-10" tabindex="-1"></a>       <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fu">min</span>(LD1c<span class="sc">$</span>LD1, <span class="at">na.rm=</span>T),<span class="fu">max</span>(LD1c<span class="sc">$</span>LD1, <span class="at">na.rm=</span>T))))</span>
<span id="cb9-11"><a href="#cb9-11" tabindex="-1"></a>  <span class="fu">box</span>()</span>
<span id="cb9-12"><a href="#cb9-12" tabindex="-1"></a>  <span class="fu">mtext</span>(<span class="fu">levels</span>(LD1c<span class="sc">$</span>Rock)[i],<span class="dv">3</span>,<span class="sc">-</span><span class="fl">1.55</span>,<span class="at">adj=</span><span class="fl">0.505</span>, <span class="at">cex =</span> <span class="fl">0.85</span>, <span class="at">font =</span> <span class="dv">2</span>, <span class="at">col=</span><span class="dv">14</span>)</span>
<span id="cb9-13"><a href="#cb9-13" tabindex="-1"></a>  <span class="fu">mtext</span>(<span class="fu">levels</span>(LD1c<span class="sc">$</span>Rock)[i],<span class="dv">3</span>,<span class="sc">-</span><span class="fl">1.5</span>, <span class="at">cex =</span> <span class="fl">0.85</span>, <span class="at">font =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="dv">11</span>)</span>
<span id="cb9-14"><a href="#cb9-14" tabindex="-1"></a>  <span class="cf">if</span>(i<span class="sc">==</span><span class="dv">1</span>) <span class="fu">mtext</span>(<span class="st">&quot;(a) Closed data&quot;</span>, <span class="dv">3</span>, <span class="fl">0.5</span>, <span class="at">font=</span><span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">1.4</span>, <span class="at">col =</span> <span class="dv">11</span>)</span>
<span id="cb9-15"><a href="#cb9-15" tabindex="-1"></a>}</span>
<span id="cb9-16"><a href="#cb9-16" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" tabindex="-1"></a>LD1o <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Rock=</span><span class="fu">as.character</span>(Hallberg<span class="sc">$</span>Rock),<span class="at">LD1=</span>predOpen<span class="sc">$</span>x[,<span class="dv">1</span>])</span>
<span id="cb9-18"><a href="#cb9-18" tabindex="-1"></a>LD1o<span class="sc">$</span>Rock <span class="ot">&lt;-</span> <span class="fu">factor</span>(LD1o<span class="sc">$</span>Rock, <span class="at">levels=</span><span class="fu">levels</span>(Hallberg<span class="sc">$</span>Rock))</span>
<span id="cb9-19"><a href="#cb9-19" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nlevels</span>(LD1o<span class="sc">$</span>Rock)){</span>
<span id="cb9-20"><a href="#cb9-20" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">subset</span>(LD1o, <span class="at">subset=</span>LD1o<span class="sc">$</span>Rock<span class="sc">==</span><span class="fu">levels</span>(LD1o<span class="sc">$</span>Rock)[i]),</span>
<span id="cb9-21"><a href="#cb9-21" tabindex="-1"></a>       <span class="fu">hist</span>(LD1, <span class="at">main =</span> <span class="st">&quot;&quot;</span>, <span class="at">breaks =</span> <span class="fu">pretty</span>(LD1o<span class="sc">$</span>LD1, <span class="at">n=</span><span class="dv">20</span>), <span class="at">col=</span><span class="dv">4</span>,</span>
<span id="cb9-22"><a href="#cb9-22" tabindex="-1"></a>            <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fu">min</span>(LD1o<span class="sc">$</span>LD1, <span class="at">na.rm=</span>T),<span class="fu">max</span>(LD1o<span class="sc">$</span>LD1, <span class="at">na.rm=</span>T))))</span>
<span id="cb9-23"><a href="#cb9-23" tabindex="-1"></a>  <span class="fu">box</span>()</span>
<span id="cb9-24"><a href="#cb9-24" tabindex="-1"></a>  <span class="fu">mtext</span>(<span class="fu">levels</span>(LD1o<span class="sc">$</span>Rock)[i],<span class="dv">3</span>,<span class="sc">-</span><span class="fl">1.55</span>, <span class="at">adj=</span><span class="fl">0.505</span>, <span class="at">cex =</span> <span class="fl">0.85</span>, <span class="at">font =</span> <span class="dv">2</span>, <span class="at">col=</span><span class="dv">14</span>)</span>
<span id="cb9-25"><a href="#cb9-25" tabindex="-1"></a>  <span class="fu">mtext</span>(<span class="fu">levels</span>(LD1o<span class="sc">$</span>Rock)[i],<span class="dv">3</span>,<span class="sc">-</span><span class="fl">1.5</span>, <span class="at">cex =</span> <span class="fl">0.85</span>, <span class="at">font =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="dv">2</span>)</span>
<span id="cb9-26"><a href="#cb9-26" tabindex="-1"></a>  <span class="cf">if</span>(i<span class="sc">==</span><span class="dv">1</span>) <span class="fu">mtext</span>(<span class="st">&quot;(b) Open data&quot;</span>, <span class="dv">3</span>, <span class="fl">0.5</span>, <span class="at">font=</span><span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">1.4</span>, <span class="at">col =</span> <span class="dv">2</span>)</span>
<span id="cb9-27"><a href="#cb9-27" tabindex="-1"></a>}</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="lda_files/figure-html/Fig3-ldahistComp-1.png" alt="Figure 3: Histograms based on the first linear discriminant function for (a) closed and (b) open (CLR-transformed) whole-rock major element data." width="80%" />
<p class="caption">
Figure 3: Histograms based on the first linear discriminant function for
(a) closed and (b) open (CLR-transformed) whole-rock major element data.
</p>
</div>
<p> </p>
<p>The sets of histograms for closed and open data in Figure 3 both show
some separation of categories, but with overlap. Of course this only
shows the separation in one dimension, and two or more dimensions may be
needed to achieve clear separation. We will make plots showing more than
one LDA dimension later.</p>
</div>
<div id="partition-plots" class="section level3">
<h3>Partition plots</h3>
<p>Another potentially useful way of showing separation of groups in LDA
is to use a <em>partition plot</em>, accessible using the
<code>partimat()</code> function from the <code>klaR</code> R package
(Weihs <em>et al</em>. 2005).</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="fu">require</span>(klaR)</span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>),<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">mgp=</span> <span class="fu">c</span>(<span class="fl">1.3</span>,<span class="fl">0.2</span>,<span class="dv">0</span>), <span class="at">tcl=</span><span class="fl">0.2</span>, <span class="at">font.lab=</span><span class="dv">2</span>)</span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a><span class="fu">with</span>(Hallberg, </span>
<span id="cb10-4"><a href="#cb10-4" tabindex="-1"></a>     <span class="fu">drawparti</span>(Rock, TiO2, Zr, <span class="at">method=</span><span class="st">&quot;lda&quot;</span>,<span class="at">image.colors =</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">7</span>,<span class="dv">14</span>,<span class="dv">13</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>),</span>
<span id="cb10-5"><a href="#cb10-5" tabindex="-1"></a>               <span class="at">xlab =</span> <span class="fu">expression</span>(<span class="fu">bold</span>(<span class="fu">paste</span>(TiO[<span class="dv">2</span>],<span class="st">&quot; (mg/kg)&quot;</span>))), </span>
<span id="cb10-6"><a href="#cb10-6" tabindex="-1"></a>               <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">bold</span>(<span class="fu">paste</span>(Zr,<span class="st">&quot; (mg/kg)&quot;</span>))))</span>
<span id="cb10-7"><a href="#cb10-7" tabindex="-1"></a>     )</span>
<span id="cb10-8"><a href="#cb10-8" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&quot;(a)&quot;</span>, <span class="dv">3</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="at">adj=</span><span class="fl">0.05</span>, <span class="at">font=</span><span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb10-9"><a href="#cb10-9" tabindex="-1"></a><span class="fu">with</span>(Hallberg_clr, </span>
<span id="cb10-10"><a href="#cb10-10" tabindex="-1"></a>     <span class="fu">drawparti</span>(Rock, TiO2, Zr, <span class="at">method=</span><span class="st">&quot;lda&quot;</span>,<span class="at">image.colors =</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">7</span>,<span class="dv">14</span>,<span class="dv">13</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>),</span>
<span id="cb10-11"><a href="#cb10-11" tabindex="-1"></a>               <span class="at">xlab =</span> <span class="fu">expression</span>(<span class="fu">bold</span>(<span class="fu">paste</span>(TiO[<span class="dv">2</span>],<span class="st">&quot; (CLR-transformed)&quot;</span>))), </span>
<span id="cb10-12"><a href="#cb10-12" tabindex="-1"></a>               <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">bold</span>(<span class="fu">paste</span>(Zr,<span class="st">&quot; (CLR-transformed)&quot;</span>))))</span>
<span id="cb10-13"><a href="#cb10-13" tabindex="-1"></a>     )</span>
<span id="cb10-14"><a href="#cb10-14" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&quot;(b)&quot;</span>, <span class="dv">3</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="at">adj=</span><span class="fl">0.95</span>, <span class="at">font=</span><span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="lda_files/figure-html/Fig4-pplotComp-1.png" alt="Figure 4: Partition plots for (a) closed and (b) open (CLR-transformed) whole rock major element data, based on the TiO₂ and Zr contents. Filled symbols are means in each category, with red letters showing apparently mis-classified observations." width="100%" />
<p class="caption">
Figure 4: Partition plots for (a) closed and (b) open (CLR-transformed)
whole rock major element data, based on the TiO₂ and Zr contents. Filled
symbols are means in each category, with red letters showing apparently
mis-classified observations.
</p>
</div>
<p> </p>
<p>Partition plots, such as those in Figure 4, are presented for single
pairwise combinations of the variables (in this example TiO<sub>2</sub>
and Zr) used to make the LDA model. We can make different plots by
specifying different variables in the <code>drawparti()</code> function.
Each such plot can be considered to be a different view of the data
(which of course has multiple dimensions). Coloured regions delineate
each classification area. Any observation that falls within a region is
predicted to be from a specific category, with apparent
mis-classification in a different color (but we usually need more than
two dimensions for correct classification). Each plot also includes the
apparent error rate for that view of the data.</p>
<p> </p>
</div>
</div>
<div id="scatter-plots-resembling-biplots" class="section level2">
<h2>Scatter Plots resembling biplots</h2>
<p>Scatter-plots showing each variable and observation in linear
discriminant dimensions, and grouped by category, are useful for visual
assessment of how well the LDA model separates the observations.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">3.5</span>,<span class="fl">3.5</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">mgp =</span> <span class="fu">c</span>(<span class="fl">1.5</span>,<span class="fl">0.3</span>,<span class="dv">0</span>), <span class="at">tcl =</span> <span class="fl">0.25</span>,</span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>    <span class="at">lend =</span> <span class="st">&quot;square&quot;</span>, <span class="at">ljoin =</span> <span class="st">&quot;mitre&quot;</span>, <span class="at">cex.main =</span> <span class="fl">0.9</span>, <span class="at">font.lab=</span><span class="dv">2</span>)</span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a><span class="fu">palette</span>(<span class="fu">c</span>(<span class="st">&quot;black&quot;</span>, viridis<span class="sc">::</span><span class="fu">viridis</span>(<span class="dv">6</span>, <span class="at">alp=</span><span class="fl">0.7</span>, <span class="at">end=</span><span class="fl">0.99</span>), <span class="st">&quot;gray&quot;</span>,<span class="st">&quot;transparent&quot;</span>))</span>
<span id="cb11-4"><a href="#cb11-4" tabindex="-1"></a><span class="fu">plot</span>(lda_rock_clos<span class="sc">$</span>scaling[,<span class="dv">1</span>], lda_rock_clos<span class="sc">$</span>scaling[,<span class="dv">2</span>], <span class="at">type=</span><span class="st">&quot;n&quot;</span>,</span>
<span id="cb11-5"><a href="#cb11-5" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>), <span class="co"># ylim=c(-0.8,1.4), </span></span>
<span id="cb11-6"><a href="#cb11-6" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Linear Discriminant [1]&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Linear Discriminant [2]&quot;</span>, </span>
<span id="cb11-7"><a href="#cb11-7" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;(a) Variable Coefficients [LD1, LD2]&quot;</span>)</span>
<span id="cb11-8"><a href="#cb11-8" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb11-9"><a href="#cb11-9" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb11-10"><a href="#cb11-10" tabindex="-1"></a><span class="fu">text</span>(lda_rock_clos<span class="sc">$</span>scaling[,<span class="dv">1</span>],lda_rock_clos<span class="sc">$</span>scaling[,<span class="dv">2</span>],</span>
<span id="cb11-11"><a href="#cb11-11" tabindex="-1"></a>     <span class="at">labels=</span><span class="fu">names</span>(Hallberg)[<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)], <span class="at">pos =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">3</span>),</span>
<span id="cb11-12"><a href="#cb11-12" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">1.1</span>, <span class="at">col =</span> <span class="dv">2</span>, <span class="at">offset =</span> <span class="fl">0.2</span>)</span>
<span id="cb11-13"><a href="#cb11-13" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&quot;(a)&quot;</span>, <span class="dv">3</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="at">adj =</span> <span class="fl">0.95</span>, <span class="at">cex =</span> <span class="fl">1.2</span>, <span class="at">font =</span> <span class="dv">2</span>)</span>
<span id="cb11-14"><a href="#cb11-14" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" tabindex="-1"></a>ldaPred_rock_clos <span class="ot">&lt;-</span> <span class="fu">predict</span>(lda_rock_clos)</span>
<span id="cb11-16"><a href="#cb11-16" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">NROW</span>(lda_rock_clos<span class="sc">$</span>scaling)){</span>
<span id="cb11-18"><a href="#cb11-18" tabindex="-1"></a>  <span class="fu">arrows</span>(<span class="dv">0</span>,<span class="dv">0</span>,lda_rock_clos<span class="sc">$</span>scaling[i,<span class="dv">1</span>],lda_rock_clos<span class="sc">$</span>scaling[i,<span class="dv">2</span>],</span>
<span id="cb11-19"><a href="#cb11-19" tabindex="-1"></a>         <span class="at">length =</span> <span class="fl">0.1</span>, <span class="at">col =</span> <span class="dv">8</span>)</span>
<span id="cb11-20"><a href="#cb11-20" tabindex="-1"></a>}</span>
<span id="cb11-21"><a href="#cb11-21" tabindex="-1"></a></span>
<span id="cb11-22"><a href="#cb11-22" tabindex="-1"></a><span class="fu">plot</span>(ldaPred_rock_clos<span class="sc">$</span>x[,<span class="dv">1</span>], ldaPred_rock_clos<span class="sc">$</span>x[,<span class="dv">2</span>],</span>
<span id="cb11-23"><a href="#cb11-23" tabindex="-1"></a>     <span class="at">bg=</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>)[Hallberg_clr<span class="sc">$</span>Rock],</span>
<span id="cb11-24"><a href="#cb11-24" tabindex="-1"></a>     <span class="at">pch=</span><span class="fu">c</span>(<span class="dv">21</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">21</span>)[Hallberg_clr<span class="sc">$</span>Rock], <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, </span>
<span id="cb11-25"><a href="#cb11-25" tabindex="-1"></a>  <span class="at">xlab=</span><span class="st">&quot;Linear Discriminant [1]&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Linear Discriminant [2]&quot;</span>, </span>
<span id="cb11-26"><a href="#cb11-26" tabindex="-1"></a>  <span class="at">main=</span><span class="st">&quot;Predictions for Observations [LD1, LD2]&quot;</span>)</span>
<span id="cb11-27"><a href="#cb11-27" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb11-28"><a href="#cb11-28" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb11-29"><a href="#cb11-29" tabindex="-1"></a><span class="co"># text(ldaPred_rock_clos$x[,1], ldaPred_rock_clos$x[,2], </span></span>
<span id="cb11-30"><a href="#cb11-30" tabindex="-1"></a><span class="co">#      labels=as.character(Hallberg$Rock), col=c(2,4,6,3,12)[Hallberg$Rock],</span></span>
<span id="cb11-31"><a href="#cb11-31" tabindex="-1"></a><span class="co">#      pos=1, offset=0.15, cex=0.65)</span></span>
<span id="cb11-32"><a href="#cb11-32" tabindex="-1"></a><span class="co"># legend(&quot;bottomright&quot;,legend=levels(Hallberg$Rock)[6:13],</span></span>
<span id="cb11-33"><a href="#cb11-33" tabindex="-1"></a><span class="co">#        ncol = 2, col=c(6:13), pch=c(5:12), pt.lwd = 2,</span></span>
<span id="cb11-34"><a href="#cb11-34" tabindex="-1"></a><span class="co">#        title=expression(bold(&quot;Rock Type&quot;)),</span></span>
<span id="cb11-35"><a href="#cb11-35" tabindex="-1"></a><span class="co">#        bty=&quot;n&quot;, inset=0.01, </span></span>
<span id="cb11-36"><a href="#cb11-36" tabindex="-1"></a><span class="co">#        pt.cex=c(1.8,1.8,2,2,1.3), cex=0.9)</span></span>
<span id="cb11-37"><a href="#cb11-37" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&quot;(b)&quot;</span>, <span class="dv">3</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="at">adj =</span> <span class="fl">0.95</span>, <span class="at">cex =</span> <span class="fl">1.2</span>, <span class="at">font =</span> <span class="dv">2</span>)</span>
<span id="cb11-38"><a href="#cb11-38" tabindex="-1"></a></span>
<span id="cb11-39"><a href="#cb11-39" tabindex="-1"></a><span class="fu">plot</span>(ldaPred_rock_clos<span class="sc">$</span>x[,<span class="dv">1</span>], ldaPred_rock_clos<span class="sc">$</span>x[,<span class="dv">3</span>], </span>
<span id="cb11-40"><a href="#cb11-40" tabindex="-1"></a>     <span class="at">bg=</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>)[Hallberg_clr<span class="sc">$</span>Rock],</span>
<span id="cb11-41"><a href="#cb11-41" tabindex="-1"></a>     <span class="at">pch=</span><span class="fu">c</span>(<span class="dv">21</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">21</span>)[Hallberg_clr<span class="sc">$</span>Rock], <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, </span>
<span id="cb11-42"><a href="#cb11-42" tabindex="-1"></a>  <span class="at">xlab=</span><span class="st">&quot;Linear Discriminant [1]&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Linear Discriminant [3]&quot;</span>, </span>
<span id="cb11-43"><a href="#cb11-43" tabindex="-1"></a>  <span class="at">main=</span><span class="st">&quot;Predictions for Observations [LD1, LD3]&quot;</span>)</span>
<span id="cb11-44"><a href="#cb11-44" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb11-45"><a href="#cb11-45" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb11-46"><a href="#cb11-46" tabindex="-1"></a><span class="co"># text(ldaPred_rock_clos$x[,1], ldaPred_rock_clos$x[,3], </span></span>
<span id="cb11-47"><a href="#cb11-47" tabindex="-1"></a><span class="co">#      labels=Hallberg$Rock, col=c(1:13)[Hallberg$Rock],</span></span>
<span id="cb11-48"><a href="#cb11-48" tabindex="-1"></a><span class="co">#      pos=1, offset=0.15, cex=0.65)</span></span>
<span id="cb11-49"><a href="#cb11-49" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&quot;(c)&quot;</span>, <span class="dv">3</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="at">adj =</span> <span class="fl">0.05</span>, <span class="at">cex =</span> <span class="fl">1.2</span>, <span class="at">font =</span> <span class="dv">2</span>)</span>
<span id="cb11-50"><a href="#cb11-50" tabindex="-1"></a></span>
<span id="cb11-51"><a href="#cb11-51" tabindex="-1"></a><span class="fu">plot</span>(ldaPred_rock_clos<span class="sc">$</span>x[,<span class="dv">2</span>], ldaPred_rock_clos<span class="sc">$</span>x[,<span class="dv">4</span>],</span>
<span id="cb11-52"><a href="#cb11-52" tabindex="-1"></a>     <span class="at">bg=</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>)[Hallberg_clr<span class="sc">$</span>Rock],</span>
<span id="cb11-53"><a href="#cb11-53" tabindex="-1"></a>     <span class="at">pch=</span><span class="fu">c</span>(<span class="dv">21</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">21</span>)[Hallberg_clr<span class="sc">$</span>Rock], <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, </span>
<span id="cb11-54"><a href="#cb11-54" tabindex="-1"></a>  <span class="at">xlab=</span><span class="st">&quot;Linear Discriminant [2]&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Linear Discriminant [4]&quot;</span>, </span>
<span id="cb11-55"><a href="#cb11-55" tabindex="-1"></a>  <span class="at">main=</span><span class="st">&quot;Predictions for Observations [LD2, LD4]&quot;</span>)</span>
<span id="cb11-56"><a href="#cb11-56" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb11-57"><a href="#cb11-57" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb11-58"><a href="#cb11-58" tabindex="-1"></a><span class="co"># text(ldaPred_rock_clos$x[,2], ldaPred_rock_clos$x[,4], </span></span>
<span id="cb11-59"><a href="#cb11-59" tabindex="-1"></a><span class="co">#      labels=Hallberg$Rock, col=c(2,4,6,3,12)[Hallberg$Rock],</span></span>
<span id="cb11-60"><a href="#cb11-60" tabindex="-1"></a><span class="co">#      pos=1, offset=0.15, cex=0.65)</span></span>
<span id="cb11-61"><a href="#cb11-61" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&quot;(d)&quot;</span>, <span class="dv">3</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="at">adj=</span><span class="fl">0.05</span>, <span class="at">cex=</span><span class="fl">1.2</span>, <span class="at">font=</span><span class="dv">2</span>)</span>
<span id="cb11-62"><a href="#cb11-62" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>,<span class="at">legend=</span><span class="fu">levels</span>(Hallberg<span class="sc">$</span>Rock), <span class="at">ncol=</span><span class="dv">2</span>, <span class="at">bty=</span><span class="st">&quot;n&quot;</span>, </span>
<span id="cb11-63"><a href="#cb11-63" tabindex="-1"></a>       <span class="at">inset=</span><span class="fu">c</span>(<span class="fl">0.001</span>,<span class="fl">0.001</span>), <span class="at">pt.bg=</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>), <span class="at">pch=</span><span class="fu">c</span>(<span class="dv">21</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">21</span>), <span class="at">pt.lwd=</span><span class="dv">1</span>,</span>
<span id="cb11-64"><a href="#cb11-64" tabindex="-1"></a>    <span class="at">title=</span><span class="st">&quot;Rock Type in (b) - (d)&quot;</span>, <span class="at">pt.cex=</span><span class="fl">1.5</span>, <span class="at">cex=</span><span class="dv">1</span>, <span class="at">y.intersp=</span><span class="dv">1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="lda_files/figure-html/Fig5-LDAclos-1.png" alt="Figure 5: Linear discriminant analysis (LDA) plots for closed rock composition data: (a) variable coefficients in LD1-LD2 space, and predictions for observations in (b) LD1-LD2 space; (c) LD1-LD3 space; (d) LS2-LD4 space. Legend in (a) applies to plots in (b), (c), and (d)." width="80%" />
<p class="caption">
Figure 5: Linear discriminant analysis (LDA) plots for closed rock
composition data: (a) variable coefficients in LD1-LD2 space, and
predictions for observations in (b) LD1-LD2 space; (c) LD1-LD3 space;
(d) LS2-LD4 space. Legend in (a) applies to plots in (b), (c), and (d).
</p>
</div>
<p> </p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">3.5</span>,<span class="fl">3.5</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">mgp =</span> <span class="fu">c</span>(<span class="fl">1.5</span>,<span class="fl">0.3</span>,<span class="dv">0</span>), <span class="at">tcl =</span> <span class="fl">0.25</span>,</span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>    <span class="at">lend =</span> <span class="st">&quot;square&quot;</span>, <span class="at">ljoin =</span> <span class="st">&quot;mitre&quot;</span>, <span class="at">cex.main =</span> <span class="fl">0.9</span>, <span class="at">font.lab=</span><span class="dv">2</span>)</span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a><span class="fu">palette</span>(<span class="fu">c</span>(<span class="st">&quot;black&quot;</span>, <span class="fu">viridis</span>(<span class="dv">6</span>, <span class="at">alp=</span><span class="fl">0.7</span>, <span class="at">end=</span><span class="fl">0.99</span>), <span class="st">&quot;gray&quot;</span>,<span class="st">&quot;transparent&quot;</span>,<span class="st">&quot;white&quot;</span>))</span>
<span id="cb12-4"><a href="#cb12-4" tabindex="-1"></a><span class="fu">plot</span>(lda_rock_open<span class="sc">$</span>scaling[,<span class="dv">1</span>], lda_rock_open<span class="sc">$</span>scaling[,<span class="dv">2</span>], <span class="at">type=</span><span class="st">&quot;n&quot;</span>, </span>
<span id="cb12-5"><a href="#cb12-5" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>),  <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.2</span>,<span class="dv">1</span>), </span>
<span id="cb12-6"><a href="#cb12-6" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Linear Discriminant [1]&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Linear Discriminant [2]&quot;</span>, </span>
<span id="cb12-7"><a href="#cb12-7" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Variable Coefficients [LD1, LD2]&quot;</span>)</span>
<span id="cb12-8"><a href="#cb12-8" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>); <span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb12-9"><a href="#cb12-9" tabindex="-1"></a><span class="fu">text</span>(lda_rock_open<span class="sc">$</span>scaling[,<span class="dv">1</span>]<span class="sc">*</span><span class="fl">1.1</span>, lda_rock_open<span class="sc">$</span>scaling[,<span class="dv">2</span>]<span class="sc">*</span><span class="fl">1.1</span>, </span>
<span id="cb12-10"><a href="#cb12-10" tabindex="-1"></a>     <span class="at">labels=</span><span class="fu">names</span>(Hallberg_clr)[<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)],</span>
<span id="cb12-11"><a href="#cb12-11" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">1.1</span>, <span class="at">col =</span> <span class="dv">3</span>, <span class="at">offset=</span><span class="fl">0.2</span>, <span class="at">font=</span><span class="dv">2</span>)</span>
<span id="cb12-12"><a href="#cb12-12" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">NROW</span>(lda_rock_open<span class="sc">$</span>scaling)){</span>
<span id="cb12-13"><a href="#cb12-13" tabindex="-1"></a>  <span class="fu">arrows</span>(<span class="dv">0</span>,<span class="dv">0</span>,lda_rock_open<span class="sc">$</span>scaling[i,<span class="dv">1</span>], lda_rock_open<span class="sc">$</span>scaling[i,<span class="dv">2</span>],</span>
<span id="cb12-14"><a href="#cb12-14" tabindex="-1"></a>         <span class="at">length =</span> <span class="fl">0.1</span>, <span class="at">col =</span> <span class="dv">8</span>) }</span>
<span id="cb12-15"><a href="#cb12-15" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&quot;(a)&quot;</span>, <span class="dv">3</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="at">adj =</span> <span class="fl">0.05</span>, <span class="at">cex =</span> <span class="fl">1.2</span>, <span class="at">font =</span> <span class="dv">2</span>)</span>
<span id="cb12-16"><a href="#cb12-16" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" tabindex="-1"></a>ldaPred_rock_open <span class="ot">&lt;-</span> <span class="fu">predict</span>(lda_rock_open)</span>
<span id="cb12-18"><a href="#cb12-18" tabindex="-1"></a></span>
<span id="cb12-19"><a href="#cb12-19" tabindex="-1"></a><span class="fu">plot</span>(ldaPred_rock_open<span class="sc">$</span>x[,<span class="dv">1</span>], ldaPred_rock_open<span class="sc">$</span>x[,<span class="dv">2</span>], </span>
<span id="cb12-20"><a href="#cb12-20" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;#000000a0&quot;</span>,<span class="at">bg=</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>)[ldaPred_rock_open<span class="sc">$</span>class],</span>
<span id="cb12-21"><a href="#cb12-21" tabindex="-1"></a>     <span class="at">pch=</span><span class="fu">c</span>(<span class="dv">21</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">21</span>)[ldaPred_rock_open<span class="sc">$</span>class], <span class="at">lwd=</span><span class="dv">1</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, </span>
<span id="cb12-22"><a href="#cb12-22" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Predictions for Observations [LD1, LD2]&quot;</span>, </span>
<span id="cb12-23"><a href="#cb12-23" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Linear Discriminant [1]&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Linear Discriminant [2]&quot;</span>)</span>
<span id="cb12-24"><a href="#cb12-24" tabindex="-1"></a><span class="fu">points</span>(ldaPred_rock_open<span class="sc">$</span>x[ldaPred_rock_open<span class="sc">$</span>class<span class="sc">==</span>data0<span class="sc">$</span>Rock,<span class="dv">1</span>],</span>
<span id="cb12-25"><a href="#cb12-25" tabindex="-1"></a>       ldaPred_rock_open<span class="sc">$</span>x[ldaPred_rock_open<span class="sc">$</span>class<span class="sc">==</span>data0<span class="sc">$</span>Rock,<span class="dv">2</span>],</span>
<span id="cb12-26"><a href="#cb12-26" tabindex="-1"></a>       <span class="at">pch=</span><span class="dv">21</span>, <span class="at">cex=</span><span class="fl">0.5</span>, <span class="at">col=</span><span class="st">&quot;#ffffffa0&quot;</span>, <span class="at">bg=</span><span class="st">&quot;#000000c0&quot;</span>)</span>
<span id="cb12-27"><a href="#cb12-27" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>); <span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb12-28"><a href="#cb12-28" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&quot;(b)&quot;</span>, <span class="dv">3</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="at">adj =</span> <span class="fl">0.05</span>, <span class="at">cex =</span> <span class="fl">1.2</span>, <span class="at">font =</span> <span class="dv">2</span>)</span>
<span id="cb12-29"><a href="#cb12-29" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="at">ncol =</span> <span class="dv">1</span>, <span class="at">bty=</span><span class="st">&quot;n&quot;</span>, <span class="at">cex=</span><span class="fl">0.85</span>, <span class="at">title=</span><span class="st">&quot;Rock Type in (b)-(d)&quot;</span>, </span>
<span id="cb12-30"><a href="#cb12-30" tabindex="-1"></a>       <span class="at">legend=</span><span class="fu">c</span>(<span class="fu">substr</span>(<span class="fu">levels</span>(ldaPred_rock_open<span class="sc">$</span>class),<span class="dv">1</span>,<span class="dv">7</span>),<span class="st">&quot;dots = correct&quot;</span>), </span>
<span id="cb12-31"><a href="#cb12-31" tabindex="-1"></a>       <span class="at">pt.cex=</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="fl">1.5</span>,<span class="dv">6</span>),<span class="fl">0.5</span>), <span class="at">pt.bg=</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>,<span class="st">&quot;#000000c0&quot;</span>), <span class="at">col=</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;#000000a0&quot;</span>,<span class="dv">6</span>),<span class="dv">10</span>), </span>
<span id="cb12-32"><a href="#cb12-32" tabindex="-1"></a>       <span class="at">pch=</span><span class="fu">c</span>(<span class="dv">21</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">21</span>,<span class="dv">21</span>), <span class="at">pt.lwd=</span><span class="dv">1</span>, <span class="at">box.col=</span><span class="st">&quot;grey90&quot;</span>, <span class="at">y.intersp=</span><span class="fl">0.95</span>, <span class="at">box.lwd=</span><span class="dv">2</span>)</span>
<span id="cb12-33"><a href="#cb12-33" tabindex="-1"></a></span>
<span id="cb12-34"><a href="#cb12-34" tabindex="-1"></a><span class="fu">plot</span>(ldaPred_rock_open<span class="sc">$</span>x[,<span class="dv">1</span>], ldaPred_rock_open<span class="sc">$</span>x[,<span class="dv">3</span>], </span>
<span id="cb12-35"><a href="#cb12-35" tabindex="-1"></a>     <span class="at">bg=</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>)[ldaPred_rock_open<span class="sc">$</span>class],</span>
<span id="cb12-36"><a href="#cb12-36" tabindex="-1"></a>     <span class="at">pch=</span><span class="fu">c</span>(<span class="dv">21</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">21</span>)[ldaPred_rock_open<span class="sc">$</span>class], <span class="at">lwd=</span><span class="dv">1</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, </span>
<span id="cb12-37"><a href="#cb12-37" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Predictions for Observations [LD1, LD3]&quot;</span>, </span>
<span id="cb12-38"><a href="#cb12-38" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Linear Discriminant [1]&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Linear Discriminant [3]&quot;</span>)</span>
<span id="cb12-39"><a href="#cb12-39" tabindex="-1"></a><span class="fu">points</span>(ldaPred_rock_open<span class="sc">$</span>x[ldaPred_rock_open<span class="sc">$</span>class<span class="sc">==</span>data0<span class="sc">$</span>Rock,<span class="dv">1</span>],</span>
<span id="cb12-40"><a href="#cb12-40" tabindex="-1"></a>       ldaPred_rock_open<span class="sc">$</span>x[ldaPred_rock_open<span class="sc">$</span>class<span class="sc">==</span>data0<span class="sc">$</span>Rock,<span class="dv">3</span>],</span>
<span id="cb12-41"><a href="#cb12-41" tabindex="-1"></a>       <span class="at">pch=</span><span class="dv">21</span>, <span class="at">cex=</span><span class="fl">0.5</span>, <span class="at">col=</span><span class="st">&quot;#ffffffa0&quot;</span>, <span class="at">bg=</span><span class="st">&quot;#000000c0&quot;</span>)</span>
<span id="cb12-42"><a href="#cb12-42" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>); <span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb12-43"><a href="#cb12-43" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&quot;(c)&quot;</span>, <span class="dv">3</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="at">adj =</span> <span class="fl">0.05</span>, <span class="at">cex =</span> <span class="fl">1.2</span>, <span class="at">font =</span> <span class="dv">2</span>)</span>
<span id="cb12-44"><a href="#cb12-44" tabindex="-1"></a></span>
<span id="cb12-45"><a href="#cb12-45" tabindex="-1"></a><span class="fu">plot</span>(ldaPred_rock_open<span class="sc">$</span>x[,<span class="dv">2</span>], ldaPred_rock_open<span class="sc">$</span>x[,<span class="dv">4</span>], </span>
<span id="cb12-46"><a href="#cb12-46" tabindex="-1"></a>     <span class="at">bg=</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>)[ldaPred_rock_open<span class="sc">$</span>class],</span>
<span id="cb12-47"><a href="#cb12-47" tabindex="-1"></a>     <span class="at">pch=</span><span class="fu">c</span>(<span class="dv">21</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">21</span>)[ldaPred_rock_open<span class="sc">$</span>class], <span class="at">lwd=</span><span class="dv">1</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, </span>
<span id="cb12-48"><a href="#cb12-48" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Predictions for Observations [LD2, LD4]&quot;</span>, </span>
<span id="cb12-49"><a href="#cb12-49" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Linear Discriminant [2]&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Linear Discriminant [4]&quot;</span>)</span>
<span id="cb12-50"><a href="#cb12-50" tabindex="-1"></a><span class="fu">points</span>(ldaPred_rock_open<span class="sc">$</span>x[ldaPred_rock_open<span class="sc">$</span>class<span class="sc">==</span>data0<span class="sc">$</span>Rock,<span class="dv">2</span>],</span>
<span id="cb12-51"><a href="#cb12-51" tabindex="-1"></a>       ldaPred_rock_open<span class="sc">$</span>x[ldaPred_rock_open<span class="sc">$</span>class<span class="sc">==</span>data0<span class="sc">$</span>Rock,<span class="dv">4</span>],</span>
<span id="cb12-52"><a href="#cb12-52" tabindex="-1"></a>       <span class="at">pch=</span><span class="dv">21</span>, <span class="at">cex=</span><span class="fl">0.5</span>, <span class="at">col=</span><span class="st">&quot;#ffffffa0&quot;</span>, <span class="at">bg=</span><span class="st">&quot;#000000c0&quot;</span>)</span>
<span id="cb12-53"><a href="#cb12-53" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>); <span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb12-54"><a href="#cb12-54" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&quot;(d)&quot;</span>, <span class="dv">3</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="at">adj =</span> <span class="fl">0.95</span>, <span class="at">cex =</span> <span class="fl">1.2</span>, <span class="at">font =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="lda_files/figure-html/Fig6-LDAopen-1.png" alt="Figure 6: Linear discriminant analysis (LDA) plots for open (CLR-transformed) rock composition data: (a) variable coefficients in LD1-LD2 space, and predictions for observations (showing correct classes) in (b) LD1-LD2 space; (c) LD1-LD3 space; (d) LS2-LD3 space. Legend in (a) applies to plots (b), (c), and (d)." width="70%" />
<p class="caption">
Figure 6: Linear discriminant analysis (LDA) plots for open
(CLR-transformed) rock composition data: (a) variable coefficients in
LD1-LD2 space, and predictions for observations (showing correct
classes) in (b) LD1-LD2 space; (c) LD1-LD3 space; (d) LS2-LD3 space.
Legend in (a) applies to plots (b), (c), and (d).
</p>
</div>
<p> </p>
<p>From the plots in Figure 5 and Figure 6, we can see that the LDA
models obtained are certainly able to separate observations by the
selected factor. Firstly, however, there is a lot of clustering of the
predictor variables in Figure 5(a), which may relate to spurious
relationships between variables caused by compositional closure. This
clustering is not so pronounced in Figure 6(a), since the closure has
been removed by CLR-transformation.</p>
<p>Out of the combinations of LDA dimensions selected, the best
separation is with LD2 <em>vs</em>. LD1, which is not surprising since
these dimensions together account for about 95% of the between-groups
variance – for both closed and open data. There is a lot of apparent
overlap, but we can not see the true separation in only 2 dimensions.
The LDA performed on open data may result in slightly clearer separation
of samples by Rock category than LDA using closed data, but without a
multidimensional view this is also hard to be sure about.</p>
</div>
<div
id="inspecting-the-agreement-between-actual-and-predicted-categories-in-lda"
class="section level2">
<h2>Inspecting the agreement between actual and predicted categories in
LDA</h2>
<p>To do this easily we just make an R data frame with columns for the
actual categories (from the original data frame) and the predicted
categories (from the prediction objects we just made). We add a column
telling us if these two columns match in each row (which we can see
easily, but we use this column to calculate a numerical prediction
accuracy).</p>
<p>We need to make objects containing the LDA predictions:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a>ldaPred_rock_clos <span class="ot">&lt;-</span> <span class="fu">predict</span>(lda_rock_clos)</span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a>ldaPred_rock_open <span class="ot">&lt;-</span> <span class="fu">predict</span>(lda_rock_open)</span></code></pre></div>
<p>The code below uses the <code>head()</code> function to inspect the
first few rows of each comparison, but we could easily look at the whole
comparison data frames using <code>print()</code>.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a>closComp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Actual =</span> <span class="fu">as.character</span>(Hallberg<span class="sc">$</span>Rock),</span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a>                       <span class="at">Predicted =</span> <span class="fu">as.character</span>(ldaPred_rock_clos<span class="sc">$</span>class))</span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a>closComp<span class="sc">$</span>test <span class="ot">&lt;-</span> <span class="fu">as.character</span>(Hallberg_clr<span class="sc">$</span>Rock) <span class="sc">==</span> </span>
<span id="cb14-4"><a href="#cb14-4" tabindex="-1"></a>  <span class="fu">as.character</span>(ldaPred_rock_clos<span class="sc">$</span>class)</span>
<span id="cb14-5"><a href="#cb14-5" tabindex="-1"></a>k <span class="ot">=</span> <span class="fu">length</span>(<span class="fu">which</span>(closComp<span class="sc">$</span>test <span class="sc">==</span> <span class="cn">TRUE</span>))</span>
<span id="cb14-6"><a href="#cb14-6" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Predictions by LDA using closed data:&quot;</span>,k,<span class="st">&quot;out of&quot;</span>,<span class="fu">NROW</span>(Hallberg_clr),</span>
<span id="cb14-7"><a href="#cb14-7" tabindex="-1"></a>    <span class="st">&quot;=&quot;</span>,<span class="fu">paste0</span>(<span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span>k<span class="sc">/</span><span class="fu">NROW</span>(Hallberg_clr),<span class="dv">1</span>),<span class="st">&quot;% correct</span><span class="sc">\n</span><span class="st">&quot;</span>))</span>
<span id="cb14-8"><a href="#cb14-8" tabindex="-1"></a><span class="fu">head</span>(closComp, <span class="at">n =</span> <span class="dv">10</span>)</span>
<span id="cb14-9"><a href="#cb14-9" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" tabindex="-1"></a>openComp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Actual =</span> <span class="fu">as.character</span>(Hallberg_clr<span class="sc">$</span>Rock),</span>
<span id="cb14-11"><a href="#cb14-11" tabindex="-1"></a>                       <span class="at">Predicted =</span> <span class="fu">as.character</span>(ldaPred_rock_open<span class="sc">$</span>class))</span>
<span id="cb14-12"><a href="#cb14-12" tabindex="-1"></a>openComp<span class="sc">$</span>test <span class="ot">&lt;-</span> <span class="fu">as.character</span>(Hallberg_clr<span class="sc">$</span>Rock) <span class="sc">==</span> </span>
<span id="cb14-13"><a href="#cb14-13" tabindex="-1"></a>  <span class="fu">as.character</span>(ldaPred_rock_open<span class="sc">$</span>class)</span>
<span id="cb14-14"><a href="#cb14-14" tabindex="-1"></a>k <span class="ot">=</span> <span class="fu">length</span>(<span class="fu">which</span>(openComp<span class="sc">$</span>test <span class="sc">==</span> <span class="cn">TRUE</span>))</span>
<span id="cb14-15"><a href="#cb14-15" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st">Predictions by LDA using open data:&quot;</span>,k,<span class="st">&quot;out of&quot;</span>,<span class="fu">NROW</span>(Hallberg_clr),</span>
<span id="cb14-16"><a href="#cb14-16" tabindex="-1"></a>    <span class="st">&quot;=&quot;</span>,<span class="fu">paste0</span>(<span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span>k<span class="sc">/</span><span class="fu">NROW</span>(Hallberg_clr),<span class="dv">1</span>),<span class="st">&quot;% correct</span><span class="sc">\n</span><span class="st">&quot;</span>))</span>
<span id="cb14-17"><a href="#cb14-17" tabindex="-1"></a><span class="fu">head</span>(openComp, <span class="at">n =</span> <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## Predictions by LDA using closed data: 238 out of 353 = 67.4% correct
##            Actual Predicted  test
## 1          Basalt    Basalt  TRUE
## 2          Basalt    Basalt  TRUE
## 3          Gabbro  Dolerite FALSE
## 4          Basalt    Basalt  TRUE
## 5          Basalt  Dolerite FALSE
## 6          Basalt    Basalt  TRUE
## 7          Basalt    Basalt  TRUE
## 8          Basalt    Basalt  TRUE
## 9  High-Mg Basalt    Basalt FALSE
## 10       Dolerite  Dolerite  TRUE
##
## Predictions by LDA using open data: 295 out of 353 = 83.6% correct
##            Actual      Predicted  test
## 1          Basalt         Basalt  TRUE
## 2          Basalt       Dolerite FALSE
## 3          Gabbro         Basalt FALSE
## 4          Basalt         Basalt  TRUE
## 5          Basalt         Basalt  TRUE
## 6          Basalt         Basalt  TRUE
## 7          Basalt         Basalt  TRUE
## 8          Basalt         Basalt  TRUE
## 9  High-Mg Basalt High-Mg Basalt  TRUE
## 10       Dolerite         Basalt FALSE</code></pre>
<p>For this dataset, it seems as though LDA using open data is better at
predicting the Rock category for each observation. In the output above,
Basalt is mis-identified as Dolerite (which might make sense given the
expected compositional similarity; simplistically, dolerite is a more
coarse-grained version of basalt).</p>
<p>This kind of comparison is not very rigorous, and nor does it address
the reason we might perform a supervised classification like LDA – to
use data to predict <em>unknown</em> categories. The ability of LDA to
predict unknown categories can be addressed by validation procedures,
such as the one we investigate below.</p>
<p> </p>
</div>
<div
id="assessment-of-lda-prediction-using-a-training-validation-method"
class="section level2">
<h2>Assessment of LDA prediction using a training-validation method</h2>
<p>One way that we can get a better idea about the usefulness of our
classification models is to perform some validation. This involves
'training' the model on a subset of our data, and trying to predict the
category of a different subset using the training model.</p>
<p>This can be done quite simply, by including the
<code>CV = TRUE</code> option in the <code>lda()</code> function, which
implements 'leave one out cross validation'. Simply stated, this omits
one observation at a time, running the LDA on the remaining data each
time, and predicting the probability of the missed observation being in
each category (the <em>posterior probabilities</em>). [Each observation
is assigned to the category with the greatest posterior
probability.]</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="co"># leave-one-out cross validation for LDA</span></span>
<span id="cb16-2"><a href="#cb16-2" tabindex="-1"></a>data0 <span class="ot">&lt;-</span> Hallberg_clr</span>
<span id="cb16-3"><a href="#cb16-3" tabindex="-1"></a>data0[,<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)] <span class="ot">&lt;-</span> <span class="fu">scale</span>(data0[,<span class="fu">c</span>(<span class="dv">15</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span><span class="sc">:</span><span class="dv">37</span>)]) <span class="co"># scale just numeric variables</span></span>
<span id="cb16-4"><a href="#cb16-4" tabindex="-1"></a>lda_rock_open <span class="ot">&lt;-</span> <span class="fu">lda</span>(<span class="at">formula =</span> Rock <span class="sc">~</span> SiO2 <span class="sc">+</span> TiO2 <span class="sc">+</span> Al2O3 <span class="sc">+</span> Fe2O3 <span class="sc">+</span> FeO <span class="sc">+</span> MnO <span class="sc">+</span> </span>
<span id="cb16-5"><a href="#cb16-5" tabindex="-1"></a>                               MgO <span class="sc">+</span> CaO <span class="sc">+</span> Na2O <span class="sc">+</span> K2O <span class="sc">+</span> P2O5 <span class="sc">+</span> Co <span class="sc">+</span> Cr <span class="sc">+</span> Cu <span class="sc">+</span> </span>
<span id="cb16-6"><a href="#cb16-6" tabindex="-1"></a>                               Ni <span class="sc">+</span> Rb <span class="sc">+</span> Sr <span class="sc">+</span> TiO2 <span class="sc">+</span> V <span class="sc">+</span> Y <span class="sc">+</span> Zn <span class="sc">+</span> Zr, </span>
<span id="cb16-7"><a href="#cb16-7" tabindex="-1"></a>                     <span class="at">data =</span> data0,</span>
<span id="cb16-8"><a href="#cb16-8" tabindex="-1"></a>                     <span class="at">prior =</span> <span class="fu">as.numeric</span>(<span class="fu">summary</span>(data0<span class="sc">$</span>Rock))<span class="sc">/</span><span class="fu">nrow</span>(data0), </span>
<span id="cb16-9"><a href="#cb16-9" tabindex="-1"></a>                     <span class="at">CV=</span><span class="cn">TRUE</span>) </span>
<span id="cb16-10"><a href="#cb16-10" tabindex="-1"></a>preds <span class="ot">&lt;-</span> <span class="fu">apply</span>(lda_rock_open<span class="sc">$</span>posterior, <span class="at">MARGIN =</span> <span class="dv">1</span>,</span>
<span id="cb16-11"><a href="#cb16-11" tabindex="-1"></a>      <span class="at">FUN =</span> <span class="cf">function</span>(x){<span class="fu">levels</span>(lda_rock_open<span class="sc">$</span>class)[<span class="fu">which</span>(x<span class="sc">==</span><span class="fu">max</span>(x, <span class="at">na.rm=</span><span class="cn">TRUE</span>))]})</span>
<span id="cb16-12"><a href="#cb16-12" tabindex="-1"></a>obsvs <span class="ot">&lt;-</span> data0<span class="sc">$</span>Rock</span>
<span id="cb16-13"><a href="#cb16-13" tabindex="-1"></a>matches <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Pred_class=</span>preds, <span class="at">Actual_class=</span>obsvs, <span class="at">Match=</span>preds<span class="sc">==</span>obsvs)</span>
<span id="cb16-14"><a href="#cb16-14" tabindex="-1"></a><span class="fu">flextable</span>(matches[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>,]) <span class="sc">|&gt;</span> <span class="fu">bold</span>(<span class="at">part=</span><span class="st">&quot;header&quot;</span>) <span class="sc">|&gt;</span> <span class="fu">width</span>(<span class="at">width=</span><span class="fu">c</span>(<span class="fl">4.8</span>,<span class="fl">2.8</span>,<span class="fl">3.8</span>), <span class="at">unit=</span><span class="st">&quot;cm&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb16-15"><a href="#cb16-15" tabindex="-1"></a>  <span class="fu">set_header_labels</span>(<span class="at">Pred_class=</span><span class="st">&quot;Predicted class&quot;</span>, <span class="at">Actual_class=</span><span class="st">&quot;Actual class&quot;</span>, </span>
<span id="cb16-16"><a href="#cb16-16" tabindex="-1"></a>                    <span class="at">Match=</span><span class="st">&quot;Is LDA correct?&quot;</span>) <span class="sc">|&gt;</span> <span class="fu">padding</span>(<span class="at">padding=</span><span class="fl">0.5</span>,<span class="at">part=</span><span class="st">&quot;all&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb16-17"><a href="#cb16-17" tabindex="-1"></a>  <span class="fu">set_caption</span>(<span class="at">caption=</span><span class="st">&quot;Table 2: Matches between LDA model and actual data based on CLR-transformed major element concentrations in the whole rock dataset compiled by Hallberg (2006). Only the first 20 observations are shown.&quot;</span>)</span></code></pre></div>
<template id="801ed83f-a5c7-43f9-9ee0-cbd1798ae119"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  border-color: transparent;
  caption-side: top;
}
.tabwid-caption-bottom table{
  caption-side: bottom;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
.katex-display {
    margin: 0 0 !important;
}
</style><div class="tabwid"><style>.cl-412b3836{}.cl-411cebe6{font-family:'Arial';font-size:10pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-411cebfa{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4123274a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:0.5pt;padding-top:0.5pt;padding-left:0.5pt;padding-right:0.5pt;line-height: 1;background-color:transparent;}.cl-41232768{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:0.5pt;padding-top:0.5pt;padding-left:0.5pt;padding-right:0.5pt;line-height: 1;background-color:transparent;}.cl-41233e38{width:1.89in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-41233e39{width:1.102in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-41233e42{width:1.496in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-41233e56{width:1.89in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-41233e60{width:1.102in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-41233e61{width:1.496in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-41233e74{width:1.89in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-41233e7e{width:1.102in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-41233e88{width:1.496in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-41179cae{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}</style><table class='cl-412b3836'><caption><span class="cl-41179cae">Table 2: Matches between LDA model and actual data based on CLR-transformed major element concentrations in the whole rock dataset compiled by Hallberg (2006). Only the first 20 observations are shown.</span></caption><thead><tr style="overflow-wrap:break-word;"><td class="cl-41233e38"><p class="cl-4123274a"><span class="cl-411cebe6">Predicted class</span></p></td><td class="cl-41233e39"><p class="cl-4123274a"><span class="cl-411cebe6">Actual class</span></p></td><td class="cl-41233e42"><p class="cl-41232768"><span class="cl-411cebe6">Is LDA correct?</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">TRUE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Dolerite</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">FALSE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Gabbro</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">FALSE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">TRUE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">TRUE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">TRUE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">TRUE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">TRUE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">High-Mg Basalt</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">High-Mg Basalt</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">TRUE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Dolerite</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">FALSE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Gabbro</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">FALSE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">TRUE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Peridotite</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Peridotite</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">TRUE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Spinel Peridotite</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Peridotite</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">FALSE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">TRUE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Peridotite</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Peridotite</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">TRUE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Spinel Peridotite</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Peridotite</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">FALSE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Peridotite</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Peridotite</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">TRUE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e56"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e60"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e61"><p class="cl-41232768"><span class="cl-411cebfa">TRUE</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-41233e74"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e7e"><p class="cl-4123274a"><span class="cl-411cebfa">Basalt</span></p></td><td class="cl-41233e88"><p class="cl-41232768"><span class="cl-411cebfa">TRUE</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="cd9306c5-6115-4b65-9581-2daf9a8ecb3d"></div>
<script>
var dest = document.getElementById("cd9306c5-6115-4b65-9581-2daf9a8ecb3d");
var template = document.getElementById("801ed83f-a5c7-43f9-9ee0-cbd1798ae119");
var caption = template.content.querySelector("caption");
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

<p> </p>
<p>Below we use a related method, using <em>training</em> and
<em>validation</em> subsets of our data. The idea here is that we divide
the dataset into two (the code below splits the data in half, but other
splits could be used, <em>e.g</em>. 0.75:0.25). The first subset of the
data is used to generate an LDA model (<em>i.e</em>. a set of linear
discriminant functions), which are then used to try and predict the
categories in the other subset. We choose the observations making up
each subset randomly. Of course, this could give us unreliable results
if the random selection happens to be somehow unbalanced, so we repeat
the training-validation process many times to calculate an average
prediction rate.</p>
<p>One glitch that can happen is that in selecting a random subset of
the data, the subset may not include any samples from one or more
categories. This problem is more likely if our data have some categories
having relatively few observations. The code below applies an
'error-catching' condition before running the training LDA, which is
that all categories in a random subset need to be populated.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a>n0 <span class="ot">&lt;-</span> <span class="dv">200</span> <span class="co"># number of iterations</span></span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a>ftrain <span class="ot">&lt;-</span> <span class="fl">0.5</span> <span class="co"># proportion of observations in training set</span></span>
<span id="cb17-3"><a href="#cb17-3" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb17-4"><a href="#cb17-4" tabindex="-1"></a>  <span class="at">Rep =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, n0),</span>
<span id="cb17-5"><a href="#cb17-5" tabindex="-1"></a>  <span class="at">matches =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, n0),</span>
<span id="cb17-6"><a href="#cb17-6" tabindex="-1"></a>  <span class="at">non_matches =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, n0),</span>
<span id="cb17-7"><a href="#cb17-7" tabindex="-1"></a>  <span class="at">success =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, n0))</span>
<span id="cb17-8"><a href="#cb17-8" tabindex="-1"></a>train <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">NROW</span>(Hallberg), <span class="fu">round</span>(<span class="fu">NROW</span>(Hallberg) <span class="sc">*</span> ftrain,<span class="dv">0</span>))</span>
<span id="cb17-9"><a href="#cb17-9" tabindex="-1"></a><span class="co"># make vector of individual category non-matches</span></span>
<span id="cb17-10"><a href="#cb17-10" tabindex="-1"></a>matchByClass <span class="ot">&lt;-</span> </span>
<span id="cb17-11"><a href="#cb17-11" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">Match1 =</span> <span class="fu">rep</span>(<span class="dv">0</span>,<span class="fu">nlevels</span>(Hallberg<span class="sc">$</span>Rock[train]))) </span>
<span id="cb17-12"><a href="#cb17-12" tabindex="-1"></a><span class="fu">rownames</span>(matchByClass) <span class="ot">&lt;-</span> <span class="fu">levels</span>(ldaPred_rock_clos<span class="sc">$</span>class)</span>
<span id="cb17-13"><a href="#cb17-13" tabindex="-1"></a>fMatchXClass <span class="ot">&lt;-</span> </span>
<span id="cb17-14"><a href="#cb17-14" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">PctMch1 =</span> <span class="fu">rep</span>(<span class="dv">0</span>,<span class="fu">nlevels</span>(Hallberg<span class="sc">$</span>Rock[train]))) </span>
<span id="cb17-15"><a href="#cb17-15" tabindex="-1"></a><span class="fu">rownames</span>(fMatchXClass) <span class="ot">&lt;-</span> <span class="fu">levels</span>(ldaPred_rock_clos<span class="sc">$</span>class)</span>
<span id="cb17-16"><a href="#cb17-16" tabindex="-1"></a><span class="co"># make vector of cumulative category counts in Hallberg[-train] iterations</span></span>
<span id="cb17-17"><a href="#cb17-17" tabindex="-1"></a>cc0 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,<span class="fu">nlevels</span>(Hallberg<span class="sc">$</span>Rock))</span>
<span id="cb17-18"><a href="#cb17-18" tabindex="-1"></a>isOK <span class="ot">&lt;-</span> <span class="dv">0</span> ; i <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb17-19"><a href="#cb17-19" tabindex="-1"></a></span>
<span id="cb17-20"><a href="#cb17-20" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n0) {</span>
<span id="cb17-21"><a href="#cb17-21" tabindex="-1"></a>  train <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">NROW</span>(Hallberg), <span class="fu">round</span>(<span class="fu">NROW</span>(Hallberg) <span class="sc">*</span> ftrain,<span class="dv">0</span>))</span>
<span id="cb17-22"><a href="#cb17-22" tabindex="-1"></a>      <span class="co"># set condition requiring all categories to be populated</span></span>
<span id="cb17-23"><a href="#cb17-23" tabindex="-1"></a>      <span class="cf">if</span> (<span class="fu">is.na</span>(<span class="fu">match</span>(<span class="cn">NA</span>,<span class="fu">tapply</span>(Hallberg[train,]<span class="sc">$</span>SiO2, </span>
<span id="cb17-24"><a href="#cb17-24" tabindex="-1"></a>                      Hallberg[train,]<span class="sc">$</span>Rock, sd, <span class="at">na.rm=</span>T))) <span class="sc">==</span> <span class="cn">TRUE</span>) {</span>
<span id="cb17-25"><a href="#cb17-25" tabindex="-1"></a>          lda_Rock_train <span class="ot">&lt;-</span> <span class="fu">lda</span>(<span class="at">formula =</span> Rock <span class="sc">~</span> SiO2 <span class="sc">+</span> TiO2 <span class="sc">+</span> Al2O3 <span class="sc">+</span> Fe2O3 <span class="sc">+</span> FeO <span class="sc">+</span> MnO <span class="sc">+</span> </span>
<span id="cb17-26"><a href="#cb17-26" tabindex="-1"></a>                               MgO <span class="sc">+</span> CaO <span class="sc">+</span> Na2O <span class="sc">+</span> K2O <span class="sc">+</span> P2O5 <span class="sc">+</span> Co <span class="sc">+</span> Cr <span class="sc">+</span> Cu <span class="sc">+</span> </span>
<span id="cb17-27"><a href="#cb17-27" tabindex="-1"></a>                               Ni <span class="sc">+</span> Rb <span class="sc">+</span> Sr <span class="sc">+</span> TiO2 <span class="sc">+</span> V <span class="sc">+</span> Y <span class="sc">+</span> Zn <span class="sc">+</span> Zr, </span>
<span id="cb17-28"><a href="#cb17-28" tabindex="-1"></a>                          <span class="at">data =</span> Hallberg[train,],</span>
<span id="cb17-29"><a href="#cb17-29" tabindex="-1"></a>                          <span class="at">prior=</span><span class="fu">as.numeric</span>(<span class="fu">summary</span>(Hallberg<span class="sc">$</span>Rock[train]))<span class="sc">/</span></span>
<span id="cb17-30"><a href="#cb17-30" tabindex="-1"></a>                            <span class="fu">nrow</span>(Hallberg[train,]))</span>
<span id="cb17-31"><a href="#cb17-31" tabindex="-1"></a>          ldaPred_rock_clos <span class="ot">&lt;-</span> <span class="fu">predict</span>(lda_Rock_train, Hallberg[<span class="sc">-</span>train,])</span>
<span id="cb17-32"><a href="#cb17-32" tabindex="-1"></a>          isOK <span class="ot">&lt;-</span> isOK <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb17-33"><a href="#cb17-33" tabindex="-1"></a>        }</span>
<span id="cb17-34"><a href="#cb17-34" tabindex="-1"></a>  </span>
<span id="cb17-35"><a href="#cb17-35" tabindex="-1"></a>  k<span class="ot">=</span><span class="dv">0</span>               <span class="co"># number of matches</span></span>
<span id="cb17-36"><a href="#cb17-36" tabindex="-1"></a>  m0 <span class="ot">&lt;-</span>             <span class="co"># vector of individual category matches </span></span>
<span id="cb17-37"><a href="#cb17-37" tabindex="-1"></a>    <span class="fu">as.matrix</span>(<span class="fu">rep</span>(<span class="dv">0</span>,<span class="fu">nlevels</span>(Hallberg<span class="sc">$</span>Rock[train]))) </span>
<span id="cb17-38"><a href="#cb17-38" tabindex="-1"></a>  <span class="fu">rownames</span>(m0) <span class="ot">&lt;-</span> <span class="fu">levels</span>(Hallberg<span class="sc">$</span>Rock)</span>
<span id="cb17-39"><a href="#cb17-39" tabindex="-1"></a>  m1 <span class="ot">&lt;-</span>             <span class="co"># vector of fractional category matches </span></span>
<span id="cb17-40"><a href="#cb17-40" tabindex="-1"></a>    <span class="fu">as.matrix</span>(<span class="fu">rep</span>(<span class="dv">0</span>,<span class="fu">nlevels</span>(Hallberg<span class="sc">$</span>Rock[train]))) </span>
<span id="cb17-41"><a href="#cb17-41" tabindex="-1"></a>  <span class="fu">rownames</span>(m1) <span class="ot">&lt;-</span> <span class="fu">levels</span>(Hallberg<span class="sc">$</span>Rock)</span>
<span id="cb17-42"><a href="#cb17-42" tabindex="-1"></a>  <span class="cf">for</span> (jM <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">NROW</span>(Hallberg[<span class="sc">-</span>train,])) {</span>
<span id="cb17-43"><a href="#cb17-43" tabindex="-1"></a>    <span class="cf">for</span> (jS <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nlevels</span>(ldaPred_rock_clos<span class="sc">$</span>class)) {</span>
<span id="cb17-44"><a href="#cb17-44" tabindex="-1"></a>      <span class="cf">if</span>((ldaPred_rock_clos<span class="sc">$</span>class[jM] <span class="sc">==</span> <span class="fu">levels</span>(ldaPred_rock_clos<span class="sc">$</span>class)[jS]) <span class="sc">&amp;</span> </span>
<span id="cb17-45"><a href="#cb17-45" tabindex="-1"></a>         (Hallberg<span class="sc">$</span>Rock[<span class="sc">-</span>train][jM] <span class="sc">==</span> <span class="fu">levels</span>(ldaPred_rock_clos<span class="sc">$</span>class)[jS]) ) </span>
<span id="cb17-46"><a href="#cb17-46" tabindex="-1"></a>        m0[jS] <span class="ot">=</span> m0[jS] <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb17-47"><a href="#cb17-47" tabindex="-1"></a>      <span class="cf">else</span>  m0[jS] <span class="ot">=</span> m0[jS] </span>
<span id="cb17-48"><a href="#cb17-48" tabindex="-1"></a>    }</span>
<span id="cb17-49"><a href="#cb17-49" tabindex="-1"></a>    k <span class="ot">=</span> <span class="fu">sum</span>(m0)</span>
<span id="cb17-50"><a href="#cb17-50" tabindex="-1"></a>  }</span>
<span id="cb17-51"><a href="#cb17-51" tabindex="-1"></a>  cc0 <span class="ot">&lt;-</span> cc0 <span class="sc">+</span> <span class="fu">as.numeric</span>(<span class="fu">summary</span>(Hallberg<span class="sc">$</span>Rock[<span class="sc">-</span>train]))</span>
<span id="cb17-52"><a href="#cb17-52" tabindex="-1"></a>  m1 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span>m0<span class="sc">/</span><span class="fu">as.numeric</span>(<span class="fu">summary</span>(Hallberg<span class="sc">$</span>Rock[<span class="sc">-</span>train])),<span class="dv">1</span>)</span>
<span id="cb17-53"><a href="#cb17-53" tabindex="-1"></a>  matchByClass[,<span class="fu">paste0</span>(<span class="st">&quot;Match&quot;</span>,i)] <span class="ot">&lt;-</span> m0</span>
<span id="cb17-54"><a href="#cb17-54" tabindex="-1"></a>  fMatchXClass[,<span class="fu">paste0</span>(<span class="st">&quot;PctMch&quot;</span>,i)] <span class="ot">&lt;-</span> m1</span>
<span id="cb17-55"><a href="#cb17-55" tabindex="-1"></a>  <span class="co"># output to results data frame: iteration, matches, non-matches, proportion matched</span></span>
<span id="cb17-56"><a href="#cb17-56" tabindex="-1"></a>  results[i,] <span class="ot">&lt;-</span> <span class="fu">c</span>(i, k, <span class="fu">NROW</span>(Hallberg[<span class="sc">-</span>train,])<span class="sc">-</span>k, </span>
<span id="cb17-57"><a href="#cb17-57" tabindex="-1"></a>                   <span class="fu">signif</span>(k<span class="sc">/</span><span class="fu">NROW</span>(Hallberg[<span class="sc">-</span>train,]),<span class="dv">3</span>))</span>
<span id="cb17-58"><a href="#cb17-58" tabindex="-1"></a>}</span>
<span id="cb17-59"><a href="#cb17-59" tabindex="-1"></a><span class="co"># Output code block</span></span>
<span id="cb17-60"><a href="#cb17-60" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste</span>(<span class="st">&quot;[Based on&quot;</span>, n0, <span class="st">&quot;random subsets of&quot;</span>,<span class="fu">paste0</span>(<span class="dv">100</span><span class="sc">*</span>ftrain,<span class="st">&quot;%&quot;</span>),</span>
<span id="cb17-61"><a href="#cb17-61" tabindex="-1"></a>          <span class="st">&quot;of the dataset to train LDA model</span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb17-62"><a href="#cb17-62" tabindex="-1"></a>     <span class="st">&quot;      to predict remaining observations]</span><span class="sc">\n</span><span class="st">&quot;</span>))</span>
<span id="cb17-63"><a href="#cb17-63" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">&quot;Number of obs. in random subsets =&quot;</span>,<span class="fu">NROW</span>(train),</span>
<span id="cb17-64"><a href="#cb17-64" tabindex="-1"></a>      <span class="st">&quot; (predicting&quot;</span>,<span class="fu">NROW</span>(Hallberg)<span class="sc">-</span><span class="fu">NROW</span>(train),<span class="st">&quot;samples)</span><span class="sc">\n</span><span class="st">&quot;</span>)</span>
<span id="cb17-65"><a href="#cb17-65" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">numSummary</span>(results[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>], <span class="at">statistics=</span><span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>,<span class="st">&quot;sd&quot;</span>))<span class="sc">$</span>table)</span>
<span id="cb17-66"><a href="#cb17-66" tabindex="-1"></a>  ns0 <span class="ot">&lt;-</span> <span class="fu">numSummary</span>(results<span class="sc">$</span>success)</span>
<span id="cb17-67"><a href="#cb17-67" tabindex="-1"></a>  t0 <span class="ot">&lt;-</span> <span class="fu">t.test</span>(results<span class="sc">$</span>success)</span>
<span id="cb17-68"><a href="#cb17-68" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="fu">rep</span>(<span class="st">&quot;-\u2013-&quot;</span>,<span class="dv">24</span>),</span>
<span id="cb17-69"><a href="#cb17-69" tabindex="-1"></a>      <span class="st">&quot;</span><span class="sc">\n</span><span class="st">Stat. summary for &#39;success&#39;:</span><span class="sc">\n</span><span class="st">Mean = &quot;</span>,<span class="fu">round</span>(ns0<span class="sc">$</span>table[<span class="dv">1</span>],<span class="dv">4</span>),</span>
<span id="cb17-70"><a href="#cb17-70" tabindex="-1"></a>      <span class="st">&quot;, sd = &quot;</span>,<span class="fu">round</span>(ns0<span class="sc">$</span>table[<span class="dv">2</span>],<span class="dv">4</span>),</span>
<span id="cb17-71"><a href="#cb17-71" tabindex="-1"></a>      <span class="st">&quot;, 95% confidence interval = (&quot;</span>,</span>
<span id="cb17-72"><a href="#cb17-72" tabindex="-1"></a>      <span class="fu">signif</span>(t0<span class="sc">$</span>conf.int[<span class="dv">1</span>],<span class="dv">3</span>),<span class="st">&quot;, &quot;</span>,<span class="fu">signif</span>(t0<span class="sc">$</span>conf.int[<span class="dv">2</span>],<span class="dv">4</span>),</span>
<span id="cb17-73"><a href="#cb17-73" tabindex="-1"></a>      <span class="st">&quot;) (after &quot;</span>,i,<span class="st">&quot; reps)</span><span class="sc">\n</span><span class="st">&quot;</span>, <span class="at">sep=</span><span class="st">&quot;&quot;</span>)</span>
<span id="cb17-74"><a href="#cb17-74" tabindex="-1"></a>  <span class="fu">cat</span>(n0<span class="sc">-</span>isOK,<span class="st">&quot;iterations &#39;failed&#39; due to randomisation missing a category</span><span class="sc">\n\n</span><span class="st">&quot;</span>)</span>
<span id="cb17-75"><a href="#cb17-75" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">&quot;Fraction of matches by category over ALL iterations:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span>
<span id="cb17-76"><a href="#cb17-76" tabindex="-1"></a>  summCats <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb17-77"><a href="#cb17-77" tabindex="-1"></a>    <span class="at">Rock_Type =</span> <span class="fu">row.names</span>(matchByClass),</span>
<span id="cb17-78"><a href="#cb17-78" tabindex="-1"></a>    <span class="at">Total_Matched =</span> <span class="fu">rowSums</span>(matchByClass),</span>
<span id="cb17-79"><a href="#cb17-79" tabindex="-1"></a>    <span class="at">Actual =</span> cc0,</span>
<span id="cb17-80"><a href="#cb17-80" tabindex="-1"></a>    <span class="at">Percent_Matched =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span>(<span class="fu">rowSums</span>(matchByClass)<span class="sc">/</span>cc0),<span class="dv">1</span>),<span class="st">&quot;%&quot;</span>),</span>
<span id="cb17-81"><a href="#cb17-81" tabindex="-1"></a>    <span class="at">row.names =</span> <span class="cn">NULL</span>)</span>
<span id="cb17-82"><a href="#cb17-82" tabindex="-1"></a>  <span class="fu">print</span>(summCats)</span></code></pre></div>
<pre><code>## [Based on 200 random subsets of 50% of the dataset to train LDA model
##        to predict remaining observations]
## Number of obs. in random subsets = 176  (predicting 177 samples)
##                   mean         sd
## matches     108.730000 25.5133643
## non_matches  68.270000 25.5133643
## success       0.614305  0.1441154
## -–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–-
## Stat. summary for &#39;success&#39;:
## Mean = 0.6143, sd = 0.1441, 95% confidence interval = (0.594, 0.6344) (after 200 reps)
## 105 iterations &#39;failed&#39; due to randomisation missing a category
##
## Fraction of matches by category over ALL iterations:
##           Rock_Type Total_Matched Actual Percent_Matched
## 1            Basalt         16124  20304           79.4%
## 2          Dolerite           260   2880              9%
## 3            Gabbro             9    751            1.2%
## 4    High-Mg Basalt          4371   8600           50.8%
## 5        Peridotite           936   2565           36.5%
## 6 Spinel Peridotite            46    300           15.3%</code></pre>
<p>The number of iterations makes some difference (Figure 5)!</p>
<p>Based on Figure 7, it looks like we should run at least 50-100
iterations to get a reasonable idea of how well our LDA model performs.
More iterations are better, but it depends how long you want the
run-time to be!</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">mgp =</span> <span class="fu">c</span>(<span class="fl">1.5</span>,<span class="fl">0.2</span>,<span class="dv">0</span>), <span class="at">tcl =</span> <span class="fl">0.25</span>, <span class="at">font.lab =</span> <span class="dv">2</span>)</span>
<span id="cb19-2"><a href="#cb19-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">100</span>,<span class="dv">200</span>,<span class="dv">500</span>,<span class="dv">1000</span>),<span class="fu">c</span>(<span class="fl">0.5572</span>,<span class="fl">0.5986</span>,<span class="fl">0.5848</span>,<span class="fl">0.5847</span>,<span class="fl">0.5837</span>,<span class="fl">0.581</span>,<span class="fl">0.582</span>), </span>
<span id="cb19-3"><a href="#cb19-3" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">1.2</span>, <span class="at">log =</span> <span class="st">&quot;x&quot;</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">1400</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fl">0.45</span>,<span class="fl">0.65</span>),</span>
<span id="cb19-4"><a href="#cb19-4" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Number of iterations&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Mean accuracy \u00B1 95% CI&quot;</span>)</span>
<span id="cb19-5"><a href="#cb19-5" tabindex="-1"></a><span class="fu">arrows</span>(<span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">100</span>,<span class="dv">200</span>,<span class="dv">500</span>,<span class="dv">1000</span>),<span class="fu">c</span>(<span class="fl">0.49</span>,<span class="fl">0.58</span>,<span class="fl">0.572</span>,<span class="fl">0.574</span>,<span class="fl">0.577</span>,<span class="fl">0.576</span>,<span class="fl">0.579</span>),</span>
<span id="cb19-6"><a href="#cb19-6" tabindex="-1"></a>       <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">100</span>,<span class="dv">200</span>,<span class="dv">500</span>,<span class="dv">1000</span>),<span class="fu">c</span>(<span class="fl">0.624</span>,<span class="fl">0.617</span>,<span class="fl">0.598</span>,<span class="fl">0.595</span>,<span class="fl">0.591</span>,<span class="fl">0.586</span>,<span class="fl">0.585</span>),</span>
<span id="cb19-7"><a href="#cb19-7" tabindex="-1"></a>       <span class="at">angle =</span> <span class="dv">90</span>, <span class="at">length =</span> <span class="fl">0.1</span>, <span class="at">code =</span> <span class="dv">3</span>)</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="lda_files/figure-html/accuracy-vs-iterations-1.png" alt="Figure 7: Accuracy (shown by 95 percent CI error bars) as a function of number of train-validate iterations for an LDA model using closed whole-rock composition data." width="40%" />
<p class="caption">
Figure 7: Accuracy (shown by 95 percent CI error bars) as a function of
number of train-validate iterations for an LDA model using closed
whole-rock composition data.
</p>
</div>
<p> </p>
<p>We can run a similar validation process for the CLR-transformed data
(we don't show the <code>code</code>, as it's effectively identical to
the code for validation of LDA for closed data, but with references to
<code>Hallberg</code> replaced with <code>Hallberg_clr</code>).</p>
<pre><code>## [Based on 200 random subsets of 50% of the dataset to train LDA model
##        to predict remaining observations]
## Number of obs. in random subsets = 176  (predicting 177 samples)
##                   mean         sd
## matches     107.660000 26.4277606
## non_matches  69.340000 26.4277606
## success       0.608235  0.1493162
## -–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–--–-
## Stat. summary for &#39;success&#39;:
## Mean = 0.6082, sd = 0.1493, 95% confidence interval = (0.587, 0.6291) (after 200 reps)
## 113 iterations &#39;failed&#39; due to randomisation missing a category
##
## Fraction of matches by category over ALL iterations:
##           Rock_Type Total_Matched Actual Percent_Matched
## 1            Basalt         15979  20236             79%
## 2          Dolerite           232   2911              8%
## 3            Gabbro             3    716            0.4%
## 4    High-Mg Basalt          4293   8609           49.9%
## 5        Peridotite           980   2624           37.3%
## 6 Spinel Peridotite            45    304           14.8%</code></pre>
<p> </p>
<p>If we compare the validation output for the open data with the
results for closed data, we see slightly better overall accuracy for
open data. Both closed and open data generated successful predictions
&gt; 60% of the time, with a slightly greater standard deviation for LDA
based on open data.</p>
<p>There were small differences (in this validation exercise), between
closed and open data, in the ability of LDA to predict specific
categories. Open-data LDA seemed better at predicting most categories;
neither open- or closed-data LDA was good at predicting if a rock was
Gabbro.</p>
<p> </p>
<p>An issue that we haven't considered yet is whether all the variables
we used for prediction are necessary to discriminate the categories in
our data (some are collinear, based on Figure 2). The R package
<code>klaR</code> (Weihs <em>et al</em>. 2005) includes the
<code>stepclass()</code> function, which enables us to refine an LDA
model, using a procedure similar to stepwise selection of predictors in
multiple regression. The next chunk of code implements this
approach.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a>minimp <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.0005</span>,<span class="fl">0.001</span>,<span class="fl">0.002</span>,<span class="fl">0.003</span>,<span class="fl">0.005</span>,<span class="fl">0.01</span>) ; j <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb21-2"><a href="#cb21-2" tabindex="-1"></a><span class="co"># for(j in 1:length(minimp)){</span></span>
<span id="cb21-3"><a href="#cb21-3" tabindex="-1"></a>  stepwise.lda <span class="ot">&lt;-</span> <span class="fu">stepclass</span>(<span class="at">formula =</span> Rock <span class="sc">~</span> SiO2 <span class="sc">+</span> TiO2 <span class="sc">+</span> Al2O3 <span class="sc">+</span> Fe2O3 <span class="sc">+</span> FeO <span class="sc">+</span> MnO <span class="sc">+</span> </span>
<span id="cb21-4"><a href="#cb21-4" tabindex="-1"></a>                               MgO <span class="sc">+</span> CaO <span class="sc">+</span> Na2O <span class="sc">+</span> K2O <span class="sc">+</span> P2O5 <span class="sc">+</span> Co <span class="sc">+</span> Cr <span class="sc">+</span> Cu <span class="sc">+</span> </span>
<span id="cb21-5"><a href="#cb21-5" tabindex="-1"></a>                               Ni <span class="sc">+</span> Rb <span class="sc">+</span> Sr <span class="sc">+</span> TiO2 <span class="sc">+</span> V <span class="sc">+</span> Y <span class="sc">+</span> Zn <span class="sc">+</span> Zr, </span>
<span id="cb21-6"><a href="#cb21-6" tabindex="-1"></a>                            <span class="at">data =</span> data0, <span class="at">output=</span><span class="cn">TRUE</span>, </span>
<span id="cb21-7"><a href="#cb21-7" tabindex="-1"></a>                            <span class="at">prior=</span><span class="fu">as.numeric</span>(<span class="fu">summary</span>(data0<span class="sc">$</span>Rock))<span class="sc">/</span><span class="fu">nrow</span>(data0), </span>
<span id="cb21-8"><a href="#cb21-8" tabindex="-1"></a>                            <span class="at">method=</span><span class="st">&quot;lda&quot;</span>, <span class="at">improvement=</span>minimp[j], </span>
<span id="cb21-9"><a href="#cb21-9" tabindex="-1"></a>                            <span class="at">direction=</span><span class="st">&quot;backward&quot;</span>, <span class="at">criterion=</span><span class="st">&quot;AS&quot;</span>)</span>
<span id="cb21-10"><a href="#cb21-10" tabindex="-1"></a>  <span class="co"># }</span></span>
<span id="cb21-11"><a href="#cb21-11" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">&quot;Stepwise model: &quot;</span>,<span class="fu">deparse</span>(stepwise.lda<span class="sc">$</span>formula)) <span class="co"># cleaner output</span></span></code></pre></div>
<pre><code>## abiltity to seperate: 0.79392;  starting variables (21): SiO2, TiO2, Al2O3, Fe2O3, FeO, MnO, MgO, CaO, Na2O, K2O, P2O5, Co, Cr, Cu, Ni, Rb, Sr, V, Y, Zn, Zr
## abiltity to seperate: 0.79392;  out: &quot;MgO&quot;;  variables (20): SiO2, TiO2, Al2O3, Fe2O3, FeO, MnO, CaO, Na2O, K2O, P2O5, Co, Cr, Cu, Ni, Rb, Sr, V, Y, Zn, Zr
##
##  hr.elapsed min.elapsed sec.elapsed
##        0.00        0.00        2.26
##
## Stepwise model:  Rock ~ SiO2 + TiO2 + Al2O3 + Fe2O3 + FeO + MnO + CaO + Na2O +      K2O + P2O5 + Co + Cr + Cu + Ni + Rb + Sr + V + Y + Zn + Zr</code></pre>
<p> </p>
<p>The ‘full’ LDA model had 21 predictors, but the stepwise model
retains fewer predictors, depending on individual code runs and/or
choice of options (see below). For example, the <code>stepclass()</code>
function does not remove the same variable first every time, using
<code>"backward"</code> predictor selection (we can change this to
<code>"both"</code>, but <code>"backward"</code> makes sense if we start
with a ‘full’ LDA model).</p>
<p>If we run the code above repeatedly, we get different results. We
also get different results if we change the options in
<code>stepclass()</code> (for example, the default tolerance specified
by <code>improvement=</code> is 0.05, which I've found to not be
sensitive enough). We can also specify different criteria to optimise;
the code uses <code>criterion="AS"</code>, which is ‘ability to
separate’, but we can choose others, such as correctness rate
(<code>"CR"</code>, the default), accuracy <code>"AC"</code>, or
confidence <code>"CF"</code>. For full details run
<code>?klaR::stepclass</code>. If you copy the code above, uncomment the
lines beginning with <code>#</code>, and run, you can see what the
effect of changing the improvement tolerance is.</p>
<p> </p>
<p>Overall, Linear Discriminant Analysis offers a relatively simple way
to predict pre-existing categories in a dataset based on multiple
numeric variables. If we dont know what the categories should be, we
would need to use a different type of multivariate procedure, such as
one of the <a href="cluster.html">cluster analysis methods</a>.</p>
<p> </p>
<div id="references" class="section level3">
<h3>References</h3>
<p>Hallberg, J.A. (2006). <em>Greenstone chemistry from the Yilgarn
Craton</em>. Dataset ANZWA1220000718, Department of Energy, Mines,
Industry Regulation and Safety, East Perth, Western Australia <a
href="https://catalogue.data.wa.gov.au/dataset/hallberg-geochemistry"
target="_blank">https://catalogue.data.wa.gov.au/dataset/hallberg-geochemistry</a>.</p>
<p>Reimann, C., Filzmoser, P., Garrett, R. G., and Dutter, R. (2008).
<em>Statistical Data Analysis Explained: Applied Environmental
Statistics with R</em> (First ed.). John Wiley &amp; Sons, Chichester,
UK.</p>
<p>Venables, W. N. and Ripley, B. D. (2002) <em>Modern Applied
Statistics with S</em> (<code>MASS</code>). Fourth Edition. Springer,
New York. ISBN 0-387-95457-0 <a
href="http://www.stats.ox.ac.uk/pub/MASS4/"
target="_blank">http://www.stats.ox.ac.uk/pub/MASS4/</a>.</p>
<p>Weihs, C., Ligges, U., Luebke, K. and Raabe, N. (2005).
<code>klaR</code> – Analyzing German Business Cycles.
<strong>In</strong> Baier, D., Decker, R. and Schmidt-Thieme, L. (eds.).
<em>Data Analysis and Decision Support</em>, 335-343, Springer-Verlag,
Berlin.</p>
</div>
</div>

<!DOCTYPE html>

<html>
<body>
<hr style="height: 2px; background-color: #003087;" />
<p><span style="font-size:10pt"><a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank"><strong>CC-BY-SA</strong></a> • All content by <a href="https://github.com/Ratey-AtUWA" target="_blank">Ratey-AtUWA</a>. My <a href="https://www.uwa.edu.au/schools/agriculture-and-environment" target="_blank">employer</a> does not necessarily know about or endorse the content of this website.</span><br>
<span style="font-size:9pt">Created with <a href="https://bookdown.org/yihui/rmarkdown/" target="_blank"><span style="font-family: monospace;">rmarkdown</span></a> in <a href="https://posit.co/download/rstudio-desktop/" target="_blank"><span class="fa fa-registered"></span> RStudio</a>.</span></p>
</body>
</html>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
