<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Andrew Rate" />

<meta name="date" content="2024-07-23" />

<title>Statistical Relationships</title>

<script src="site_libs/header-attrs-2.27/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="site_libs/tabwid-1.1.3/tabwid.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #ffffff;
    color: #a0a0a0;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
div.sourceCode
  { color: #1f1c1b; background-color: #ffffff; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span { color: #1f1c1b; } /* Normal */
code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
code span.an { color: #ca60ca; } /* Annotation */
code span.at { color: #0057ae; } /* Attribute */
code span.bn { color: #b08000; } /* BaseN */
code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #924c9d; } /* Char */
code span.cn { color: #aa5500; } /* Constant */
code span.co { color: #898887; } /* Comment */
code span.cv { color: #0095ff; } /* CommentVar */
code span.do { color: #607880; } /* Documentation */
code span.dt { color: #0057ae; } /* DataType */
code span.dv { color: #b08000; } /* DecVal */
code span.er { color: #bf0303; text-decoration: underline; } /* Error */
code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
code span.fl { color: #b08000; } /* Float */
code span.fu { color: #644a9b; } /* Function */
code span.im { color: #ff5500; } /* Import */
code span.in { color: #b08000; } /* Information */
code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
code span.op { color: #1f1c1b; } /* Operator */
code span.ot { color: #006e28; } /* Other */
code span.pp { color: #006e28; } /* Preprocessor */
code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #ff5500; } /* SpecialString */
code span.st { color: #bf0303; } /* String */
code span.va { color: #0057ae; } /* Variable */
code span.vs { color: #bf0303; } /* VerbatimString */
code span.wa { color: #bf0303; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Sessions</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="about.html">For beginners</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Intro
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro.html">Intro</a>
    </li>
    <li>
      <a href="intro-GG.html">Intro+ggplot</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Plots
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="plots.html">Plots-baseR</a>
    </li>
    <li>
      <a href="plots-GG.html">Plots-ggplot</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Compare
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="means.html">Compare means (parametric)</a>
    </li>
    <li>
      <a href="nonparam.html">Non-parametric comparisons</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Relate
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="correl.html">Correlation</a>
    </li>
    <li>
      <a href="regression.html">Simple linear regression</a>
    </li>
    <li>
      <a href="reg-group.html">Grouped linear regression</a>
    </li>
    <li>
      <a href="reg-multi.html">Multiple linear regression</a>
    </li>
    <li>
      <a href="timeseries.html">Time series analysis</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Maps
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="maps.html">Map data with tile backgrounds</a>
    </li>
    <li>
      <a href="spatial.html">Spatial statistics</a>
    </li>
    <li>
      <a href="spat-interp.html">Spatial interpolation</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Multi
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="pca.html">Principal components analysis</a>
    </li>
    <li>
      <a href="vegan.html">Analysis of species presence-absence data</a>
    </li>
    <li>
      <a href="lda.html">Linear discriminant analysis</a>
    </li>
    <li>
      <a href="cluster.html">Cluster analysis</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Util
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="tablesPlus.html">Tables &amp; trigger value counts</a>
    </li>
    <li>
      <a href="distributions.html">Distribution checking</a>
    </li>
    <li>
      <a href="residuals.html">Regression residuals to identify contamination</a>
    </li>
    <li>
      <a href="hydrus1d.html">Hydrus-1D cheatsheet</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://www.uwa.edu.au/schools/agriculture-and-environment">UWA School of Agriculture and Environment</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->
<!DOCTYPE html>

<html>
<body>
<h3><img src="./images/2015-UWA-Full-Hor-CMYK.png" alt="UWA logo" align="right"><span style="color:#003087;">Material to support teaching in Environmental Science at The University of Western Australia</span></h3>
<h4><span style="color:#93721A;">Units ENVT3361, ENVT4461, and ENVT5503</span></h4></p>
</body>
</html>

<div id="header">



<h1 class="title toc-ignore">Statistical Relationships</h1>
<h3 class="subtitle">Grouped linear regression</h3>
<h4 class="author">Andrew Rate</h4>
<h4 class="date">2024-07-23</h4>

</div>


<style type="text/css">
  body{
  font-size: 12pt;
}
</style>
<div style="border: 2px solid #039; padding: 8px;">
<p style="text-align:center; font-size:12pt;">
<em>Relationships pages</em>: <a href="correl.html"
style="color:#04b;">Correlations</a> | <a href="regression.html"
style="color:#04b;">Simple linear regression</a> | <a
href="reg-group.html" style="color:#04b;">Grouped linear regression</a>
| <a href="reg-multi.html" style="color:#04b;">Multiple linear
regression</a>
</p>
</div>
<p> </p>
<div id="suggested-activities" class="section level3"
style="border: 2px solid #039; background-color:#e8e8e8; padding: 8px;">
<h3>Suggested activities</h3>
<p>Using the R code file provided and the <code>afs1923</code>
dataset:</p>
<ul>
<li>Run a grouped regression model,</li>
<li>Assess whether or not the grouped regression model meets the
statistical assumptions,</li>
<li>Evaluate whether a grouped regression model is a statistically
significant improvement on the comparable ungrouped model, and</li>
<li>Make sure you understand the concepts for all the statistical
methods you use, and can interpret all the output!</li>
</ul>
<p>
<a href="https://raw.githubusercontent.com/Ratey-AtUWA/Learn-R/main/afs1923.csv" target="_blank"><span
style="font-size: 12pt;">💾 The afs1923 dataset in csv (comma-separated)
format</span></a>
</p>
<p>
<a href="https://github.com/Ratey-AtUWA/Learn-R-web/raw/main/Learn-R-CODE-corr-regr-PARTS-1-2.R" target="_blank"><span
style="font-size: 12pt;">🔣 R code file for this and related workshop
sessions</span></a>
</p>
</div>
<p>
 
</p>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>In a <a href="regression.html">previous session on simple
regression</a>, we finished by suggesting that one way we could make
regression prediction more accurate was by</p>
<blockquote>
<p>allowing regression relationships to differ for different groups in
our data (defined by a factor variable) – <em>regression by
groups</em></p>
</blockquote>
<p>This session will continue or efforts to predict Cr from Al, but we
know the data were derived from analysis of samples from diverse types
of environment. For that reason, it seems reasonable to evaluate a
regression model which allows the regression coefficients (intercept and
slope) to differ for different sample types.</p>
<p>As previously, our first step is to read the data, and change
anything we need to:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a>git <span class="ot">&lt;-</span> <span class="st">&quot;https://github.com/Ratey-AtUWA/Learn-R-web/raw/main/&quot;</span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a>afs1923 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">paste0</span>(git,<span class="st">&quot;afs1923.csv&quot;</span>), <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="co"># re-order the factor levels</span></span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a>afs1923<span class="sc">$</span>Type <span class="ot">&lt;-</span> <span class="fu">factor</span>(afs1923<span class="sc">$</span>Type, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;Drain_Sed&quot;</span>,<span class="st">&quot;Lake_Sed&quot;</span>,<span class="st">&quot;Saltmarsh&quot;</span>,<span class="st">&quot;Other&quot;</span>))</span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a>afs1923<span class="sc">$</span>Type2 <span class="ot">&lt;-</span> </span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a>  <span class="fu">factor</span>(afs1923<span class="sc">$</span>Type2, </span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a>         <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;Drain_Sed&quot;</span>,<span class="st">&quot;Lake_Sed&quot;</span>,<span class="st">&quot;Saltmarsh W&quot;</span>,<span class="st">&quot;Saltmarsh E&quot;</span>,<span class="st">&quot;Other&quot;</span>))</span></code></pre></div>
<p>Next, we inspect a scatterplot of the variables which matches the
kind of regression model we intend to apply (Figure 1):</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>), <span class="at">mgp=</span><span class="fu">c</span>(<span class="fl">1.3</span>,<span class="fl">0.2</span>,<span class="dv">0</span>), <span class="at">tcl=</span><span class="fl">0.2</span>, <span class="at">font.lab=</span><span class="dv">2</span>)</span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a><span class="fu">scatterplot</span>(Cr <span class="sc">~</span> Al <span class="sc">|</span> Type2, <span class="at">data=</span>afs1923, <span class="at">smooth=</span><span class="cn">FALSE</span>,</span>
<span id="cb2-4"><a href="#cb2-4" tabindex="-1"></a>            <span class="at">col=</span><span class="fu">inferno</span>(<span class="fu">nlevels</span>(afs1923<span class="sc">$</span>Type2), <span class="at">end=</span><span class="fl">0.75</span>), <span class="at">pch=</span><span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">17</span>,<span class="dv">15</span>,<span class="dv">19</span>,<span class="dv">10</span>), </span>
<span id="cb2-5"><a href="#cb2-5" tabindex="-1"></a>            <span class="at">legend=</span><span class="fu">list</span>(<span class="at">coords=</span><span class="st">&quot;bottomright&quot;</span>, <span class="at">title=</span><span class="st">&quot;Sample type&quot;</span>))</span></code></pre></div>
<div class="figure">
<img src="reg-group_files/figure-html/sp-Cr-Al-byType-1.png" alt="Figure 1: Different relationships predicting Cr from Al depending on the sample type (data from analysis of sediments from Ashfield Flats, 2019-2023." width="480" />
<p class="caption">
Figure 1: Different relationships predicting Cr from Al depending on the
sample type (data from analysis of sediments from Ashfield Flats,
2019-2023.
</p>
</div>
</div>
<div
id="predicting-chromium-from-aluminium-using-a-regression-model-which-varies-by-groups"
class="section level2">
<h2>Predicting chromium from aluminium using a regression model which
varies by groups</h2>
<p>Note the syntax used to separate by factor categories:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a>lmCrAl_byType <span class="ot">&lt;-</span> <span class="fu">lm</span>(Cr <span class="sc">~</span> Al <span class="sc">*</span> Type2, <span class="at">data=</span>afs1923)</span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a><span class="fu">summary</span>(lmCrAl_byType)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Cr ~ Al * Type2, data = afs1923)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.644  -5.039  -0.195   4.637  47.183 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          4.069e+00  1.845e+00   2.205  0.02813 *  
## Al                   1.268e-03  7.872e-05  16.114  &lt; 2e-16 ***
## Type2Lake_Sed        1.264e+01  3.166e+00   3.994 8.04e-05 ***
## Type2Saltmarsh W     8.628e+00  3.507e+00   2.460  0.01440 *  
## Type2Saltmarsh E    -2.367e+00  3.366e+00  -0.703  0.48231    
## Type2Other           4.806e+00  6.162e+00   0.780  0.43600    
## Al:Type2Lake_Sed    -1.928e-04  1.036e-04  -1.861  0.06362 .  
## Al:Type2Saltmarsh W  1.056e-04  1.209e-04   0.873  0.38318    
## Al:Type2Saltmarsh E  3.282e-04  1.140e-04   2.880  0.00424 ** 
## Al:Type2Other       -3.437e-05  2.091e-04  -0.164  0.86954    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.444 on 325 degrees of freedom
## Multiple R-squared:  0.8362, Adjusted R-squared:  0.8317 
## F-statistic: 184.4 on 9 and 325 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This is similar output to simple linear regression in the previous
example, but the <code>Coefficients:</code> table is much more
complicated.</p>
<ul>
<li>The first two rows of the <code>Coefficients:</code> table under the
headings give the intercept and slope for the 'base case', which by
default is the first group in the factor separating the groups. In this
example the first level of the factor <code>Type</code> is
<code>Drain_Sed</code> (frustratingly, the output does not show
this).</li>
<li>The next 4 rows, starting with the factor name (<em>i.e</em>.
<code>Type2Lake_Sed</code>, <em>etc</em>.), show the <em>difference</em>
between the <strong>intercepts</strong> for <code>Lake_Sed</code>,
<code>Saltmarsh W</code>, <code>Saltmarsh E</code>, and
<code>Other</code> groups compared with the base case.</li>
<li>Similarly, the final rows, beginning with the predictor variable
name (<code>Al:Type2Lake_Sed</code>, <code>Al:Type2Saltmarsh W</code>,
<code>Al:Type2Saltmarsh E</code>, and <code>Al:Type2Other</code>), show
the <em>difference</em> between the <strong>slopes</strong> for
<code>Lake_Sed</code>, <code>Saltmarsh W</code>,
<code>Saltmarsh E</code>, and <code>Other</code> groups compared with
the base case (shown as <code>Al</code> but actually the slope for the
<code>Drain_Sed</code> group).</li>
</ul>
</div>
<div id="compare-the-two-models" class="section level2">
<h2>Compare the two models</h2>
<p>Sometimes models can have greater R<sup>2</sup> but only because
we've made them more complex by grouping our observations or by adding
more predictors. <strong>We want the simplest model possible</strong>.
We compare the models using an analysis of variance with the
<code>anova()</code> function (where the null hypothesis is equal
predictive ability). The models compared need to be
<strong>nested</strong>, that is, one is a subset of the other.</p>
<p>Before we do this, we need to re-create the simple model from a <a
href="regression.html">previous session</a>:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a>lmCrAlsimple <span class="ot">&lt;-</span> <span class="fu">lm</span>(Cr <span class="sc">~</span> Al, <span class="at">data=</span>afs1923)</span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a><span class="fu">summary</span>(lmCrAlsimple)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Cr ~ Al, data = afs1923)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -40.751  -5.349  -0.251   5.774  52.250 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 7.672e+00  1.284e+00   5.976 5.89e-09 ***
## Al          1.359e-03  3.829e-05  35.480  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.428 on 333 degrees of freedom
## Multiple R-squared:  0.7908, Adjusted R-squared:  0.7902 
## F-statistic:  1259 on 1 and 333 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>So our more complex (grouped) linear model has greater R<sup>2</sup>
(0.836) than the simple linear model (R<sup>2</sup> = 0.791). We now
perform the <code>anova</code> test to see whether this improvement is
significant:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="fu">anova</span>(lmCrAlsimple, lmCrAl_byType)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Cr ~ Al
## Model 2: Cr ~ Al * Type2
##   Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    333 29599                                  
## 2    325 23174  8    6424.7 11.263 4.366e-14 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The p-value (<code>Pr(&gt;F)</code>) is ≃ 4.4×10<sup>−14</sup>,
<em>i.e</em>. below 0.05, so we reject H<sub>0</sub> that the models
have equivalent predictive ability. In that case the model which
explains more variance in the dependent variable <code>Cr</code> is
best; that is, the <em>grouped linear model</em> with
R<sup>2</sup> = 0.836 (<em>i.e</em>., explaining 83.6% of the variance
in <code>Cr</code> based on the variance in <code>Al</code> divided into
groups by the factor <code>Type2</code>).</p>
<p id="Occam">
The choice of models should be based on an interpretation of
“<em>Occam's Razor</em>” a.k.a. the “<em>Principle of Parsimony</em>”:
</p>
<blockquote>
<p>“Plurality must never be posited without necessity.”<br />
— <em>William of Ockham (also spelled Occam) (1285 - 1348), English
theologian, logician, and Franciscan friar</em></p>
</blockquote>
<p>In practice this means that if more than one hypothesis or model
explains our data equally well, we should always choose the simplest
one.</p>
<p>Another way we can test for the most appropriate model is by using
the AIC or <em>Aikake Information Criterion</em>, which ‘penalises’ a
model having more parameters. A better model will have a lower value of
AIC, and the built-in penalty means that for equivalent models (i.e.
non-significant ANOVA) the model with more parameters will have greater
AIC, and so we should select the simpler model with the least AIC value.
For our two models, AIC shoud still be lower for the more complex model
(otherwise we are in trouble, since the ANOVA and AIC would disagree,
and then which one would we choose?). Anyway, let's find out:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a><span class="fu">AIC</span>(lmCrAlsimple, lmCrAl_byType)</span></code></pre></div>
<pre><code>##               df      AIC
## lmCrAlsimple   3 2457.942
## lmCrAl_byType 11 2391.968</code></pre>
<p>The output from the <code>AIC()</code> function shows that even
though the degrees of freedom <code>df</code> for the grouped model (11)
is much greater than for the simple model (3), the grouped model still
has a lower AIC value (≃2392) than the simple model (≃2456). So, the
ANOVA and AIC do agree after all 😌.</p>
<p>We can see a little more detail about the individual group-wise
relationships or ‘effects’ by plotting an effects plot using functions
from the <code>effects</code> package (Figure 2):</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">allEffects</span>(lmCrAl_byType))</span></code></pre></div>
<div class="figure">
<img src="reg-group_files/figure-html/plot-grouped-effects-1.png" alt="Figure 2: Effect plots showing the effects of interacting predictors `Al * Type2` on Cr, using data from sediments at Ashfield Flats 2019-2023." width="576" />
<p class="caption">
Figure 2: Effect plots showing the effects of interacting predictors
<code>Al * Type2</code> on Cr, using data from sediments at Ashfield
Flats 2019-2023.
</p>
</div>
<p>So even though the plots in Figure 1 and Figure 2 suggest that each
group has a similar <code>Cr ~ Al</code> relationship, the slopes and
intercepts differ enough between groups to give an improved prediction
over the simple model.</p>
</div>
<div id="regression-assumptions" class="section level2">
<h2>Regression assumptions</h2>
<p>The assumptions implicit in linear regression were presented in the
<a href="regression.html#assumptions">session on simple linear
regression models</a>. We run the same set of diagnostic tests on more
complex regression models as well.</p>
<div id="diagnostic-plots-for-grouped-linear-regression-cr-al-type2"
class="section level3">
<h3>Diagnostic plots for Grouped linear regression,
<code>Cr ~ Al * Type2</code></h3>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>), <span class="at">mar=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">1</span>), <span class="at">mgp=</span><span class="fu">c</span>(<span class="fl">1.3</span>,<span class="fl">0.2</span>,<span class="dv">0</span>), <span class="at">tcl=</span><span class="fl">0.2</span>, <span class="at">font.lab=</span><span class="dv">2</span>)</span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a><span class="fu">plot</span>(lmCrAl_byType, <span class="at">col=</span><span class="st">&quot;#003087&quot;</span>)</span></code></pre></div>
<div class="figure">
<img src="reg-group_files/figure-html/diag-plots-lm-grouped-1.png" alt="Diagnostic plots for a grouped linear model predicting Cr from Al with obervations grouped by sample type." width="480" />
<p class="caption">
Diagnostic plots for a grouped linear model predicting Cr from Al with
obervations grouped by sample type.
</p>
</div>
</div>
</div>
<div id="formal-statistical-tests-of-regression-assumptions"
class="section level2">
<h2>Formal statistical tests of regression assumptions</h2>
<p>As with simple linear regression, we can test all of the assumptions
with formal statistical tests (see the <a
href="regression.html#diagtests">simple linear regression session</a>
for explanations and null hypotheses).</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(lmCrAl_byType<span class="sc">$</span>residuals) <span class="co"># normality</span></span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  lmCrAl_byType$residuals
## W = 0.95798, p-value = 3.26e-08</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a><span class="fu">require</span>(lmtest)</span>
<span id="cb15-2"><a href="#cb15-2" tabindex="-1"></a><span class="fu">bgtest</span>(lmCrAl_byType) <span class="co"># autocorrelation (independence)</span></span></code></pre></div>
<pre><code>## 
##  Breusch-Godfrey test for serial correlation of order up to 1
## 
## data:  lmCrAl_byType
## LM test = 52.363, df = 1, p-value = 4.613e-13</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a><span class="fu">bptest</span>(lmCrAl_byType) <span class="co"># homoscedasticity</span></span></code></pre></div>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  lmCrAl_byType
## BP = 36.366, df = 9, p-value = 3.413e-05</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" tabindex="-1"></a><span class="fu">raintest</span>(lmCrAl_byType) <span class="co"># linearity</span></span></code></pre></div>
<pre><code>## 
##  Rainbow test
## 
## data:  lmCrAl_byType
## Rain = 0.51147, df1 = 168, df2 = 157, p-value = 1</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a><span class="fu">require</span>(car)</span>
<span id="cb21-2"><a href="#cb21-2" tabindex="-1"></a><span class="fu">outlierTest</span>(lmCrAl_byType) <span class="co"># influential observations (outliers)</span></span></code></pre></div>
<pre><code>##      rstudent unadjusted p-value Bonferroni p
## 177  6.003042         5.1884e-09   1.7381e-06
## 227 -4.192086         3.5701e-05   1.1960e-02</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">cooks.distance</span>(lmCrAl_byType)) <span class="co"># influential observations</span></span></code></pre></div>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## 0.0000000 0.0001556 0.0007584 0.0036023 0.0022228 0.1662896</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a>infl.lmCrAl <span class="ot">&lt;-</span> <span class="fu">influence.measures</span>(lmCrAl_byType)</span>
<span id="cb25-2"><a href="#cb25-2" tabindex="-1"></a>ninf <span class="ot">&lt;-</span> <span class="fu">nrow</span>(<span class="fu">summary</span>(infl.lmCrAl)) <span class="co"># number of possibly influential observations</span></span>
<span id="cb25-3"><a href="#cb25-3" tabindex="-1"></a>modform <span class="ot">&lt;-</span> <span class="fu">deparse</span>(lmCrAl_byType<span class="sc">$</span>call)</span>
<span id="cb25-4"><a href="#cb25-4" tabindex="-1"></a>rninf <span class="ot">&lt;-</span> <span class="fu">row.names</span>(<span class="fu">summary</span>(infl.lmCrAl)) <span class="co"># IDs of possibly influential observations</span></span>
<span id="cb25-5"><a href="#cb25-5" tabindex="-1"></a><span class="co"># if you run this code chunk yourself you will see the whole summary(infl.lmCrAl) output</span></span></code></pre></div>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste0</span>(<span class="st">&quot;For the model &#39;&quot;</span>, modform, <span class="st">&quot;&#39; there are &quot;</span>, ninf, </span>
<span id="cb26-2"><a href="#cb26-2" tabindex="-1"></a>           <span class="st">&quot; potentially influential observations.</span><span class="sc">\n\n</span><span class="st">&quot;</span>))</span>
<span id="cb26-3"><a href="#cb26-3" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;The&quot;</span>, ninf, <span class="st">&quot;rows containing potentially influential obervations are:</span><span class="sc">\n</span><span class="st">&quot;</span>); <span class="fu">as.integer</span>(rninf)</span></code></pre></div>
<pre><code>## For the model &#39;lm(formula = Cr ~ Al * Type2, data = afs1923)&#39; there are 36 potentially influential observations.
## 
## The 36 rows containing potentially influential obervations are:
##  [1]   2  56  92 134 137 138 139 168 177 190 196 218 219 220 227 236 245 250 251 252 273 290 291 296 297
## [26] 298 316 317 318 319 320 321 322 323 324 325</code></pre>
<p>To summarise:</p>
<div class="tabwid"><style>.cl-0609de88{}.cl-05fc0ea2{font-family:'Arial';font-size:10pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-05fc0eac{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-060183b4{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-060183d2{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:2pt;padding-right:2pt;line-height: 1;background-color:transparent;}.cl-0601ab78{width:1.575in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0601ab82{width:3.15in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0601ab8c{width:2.756in;background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0601ab8d{width:1.575in;background-color:rgba(239, 239, 239, 1.00);vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0601ab96{width:3.15in;background-color:rgba(239, 239, 239, 1.00);vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0601ab97{width:2.756in;background-color:rgba(239, 239, 239, 1.00);vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0601aba0{width:1.575in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0601abaa{width:3.15in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0601abab{width:2.756in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-0609de88'><caption style="display:table-caption;margin:0pt;text-align:left;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:0pt;padding-bottom:6pt;padding-left:0pt;padding-right:0pt;line-height: 1;background-color:transparent;"><span>Table 1: Summary of regression diagnostic tests for a grouped linear model predicting Cr from Al (grouped by Type) in sediments from Ashfield Flats Reserve, based on data from samples collected from 2019-2023.</span></caption><thead><tr style="overflow-wrap:break-word;"><th class="cl-0601ab78"><p class="cl-060183b4"><span class="cl-05fc0ea2">Test</span></p></th><th class="cl-0601ab82"><p class="cl-060183b4"><span class="cl-05fc0ea2">Assessing</span></p></th><th class="cl-0601ab8c"><p class="cl-060183b4"><span class="cl-05fc0ea2">Results</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-0601ab8d"><p class="cl-060183d2"><span class="cl-05fc0eac">Shapiro-Wilk</span></p></td><td class="cl-0601ab96"><p class="cl-060183d2"><span class="cl-05fc0eac">Are residuals normally distributed?</span></p></td><td class="cl-0601ab97"><p class="cl-060183d2"><span class="cl-05fc0eac">No (qq-plot suggests long tails)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0601aba0"><p class="cl-060183d2"><span class="cl-05fc0eac">Breusch-Godfrey</span></p></td><td class="cl-0601abaa"><p class="cl-060183d2"><span class="cl-05fc0eac">Are residuals independent?</span></p></td><td class="cl-0601abab"><p class="cl-060183d2"><span class="cl-05fc0eac">No, there is autocorrelation</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0601ab8d"><p class="cl-060183d2"><span class="cl-05fc0eac">Breusch-Pagan</span></p></td><td class="cl-0601ab96"><p class="cl-060183d2"><span class="cl-05fc0eac">Are residuals homoscedastic?</span></p></td><td class="cl-0601ab97"><p class="cl-060183d2"><span class="cl-05fc0eac">No (p&lt;0.05)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0601aba0"><p class="cl-060183d2"><span class="cl-05fc0eac">Rainbow</span></p></td><td class="cl-0601abaa"><p class="cl-060183d2"><span class="cl-05fc0eac">Is the relationship linear?</span></p></td><td class="cl-0601abab"><p class="cl-060183d2"><span class="cl-05fc0eac">Yes (p&gt;0.05)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0601ab8d"><p class="cl-060183d2"><span class="cl-05fc0eac">Outlier</span></p></td><td class="cl-0601ab96"><p class="cl-060183d2"><span class="cl-05fc0eac">Are there significant outliers (Bonferroni)?</span></p></td><td class="cl-0601ab97"><p class="cl-060183d2"><span class="cl-05fc0eac">2 points are possible outliers</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0601aba0"><p class="cl-060183d2"><span class="cl-05fc0eac">Cook's Distance</span></p></td><td class="cl-0601abaa"><p class="cl-060183d2"><span class="cl-05fc0eac">Are there any potentially influential observations?</span></p></td><td class="cl-0601abab"><p class="cl-060183d2"><span class="cl-05fc0eac">No (no values &gt; 0.5)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0601ab8d"><p class="cl-060183d2"><span class="cl-05fc0eac">Infuence Measures</span></p></td><td class="cl-0601ab96"><p class="cl-060183d2"><span class="cl-05fc0eac">Are there any potentially influential observations?</span></p></td><td class="cl-0601ab97"><p class="cl-060183d2"><span class="cl-05fc0eac">Yes (36 out of 335 observations)</span></p></td></tr></tbody></table></div>
<p>
 
</p>
<p>The summary of the diagnostic tests in Table 1 shows that not all the
formal assumptions of regression are fulfilled by our model. Even though
the model may not be strictly statistically valid, the regression output
showed that ≃ 84% of the variance in Cr could be explained by Al when
observations were grouped by sample type. So, from a practical
perspective, this grouped regression model could also be used for
prediction, and the greater R<sup>2</sup> makes it a better prediction
option than the simple model discussed in <a
href="regression.html">another session</a>.</p>
The next option would be a model which has more than one predictor
variable for our dependent variable – <a href="reg-multi.html">multiple
regression</a>.
</div>
<p>
 
</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<p>Fox, J. and Weisberg, S. (2019). <em>An {R} Companion to Applied
Regression, Third Edition</em>. Thousand Oaks CA: Sage. <a
href="https://socialsciences.mcmaster.ca/jfox/Books/Companion/"
target="_blank">https://socialsciences.mcmaster.ca/jfox/Books/Companion/</a>
(<strong>R</strong> package <code>car</code>)</p>
<p>Garnier S, Ross N, Rudis R, Camargo AP, Sciaini M, Scherer C (2021).
<em>Rvision – Colorblind-Friendly Color Maps for R</em>. R package
version 0.6.2. (<strong>R</strong> package <code>viridis</code>)</p>
<p>Reimann, C., Filzmoser, P., Garrett, R.G., Dutter, R., (2008).
<em>Statistical Data Analysis Explained: Applied Environmental
Statistics with R</em>. John Wiley &amp; Sons, Chichester, England (see
Chapter 16).</p>
<p>Zeileis, A. and Hothorn, T. (2002). Diagnostic Checking in Regression
Relationships. <em>R News</em> <strong>2</strong>(3), 7-10. <a
href="https://CRAN.R-project.org/doc/Rnews/"
target="_blank">https://CRAN.R-project.org/doc/Rnews/</a>
(<strong>R</strong> package <code>lmtest</code>)</p>
<p>
 
</p>
</div>

<!DOCTYPE html>

<html>
<body>
<hr style="height: 2px; background-color: #003087;" />
<p><span style="font-size:10pt"><a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank"><strong>CC-BY-SA</strong></a> • All content by <a href="https://github.com/Ratey-AtUWA" target="_blank">Ratey-AtUWA</a>. My <a href="https://www.uwa.edu.au/schools/agriculture-and-environment" target="_blank">employer</a> does not necessarily know about or endorse the content of this website.</span><br>
<span style="font-size:9pt">Created with <a href="https://bookdown.org/yihui/rmarkdown/" target="_blank"><span style="font-family: monospace;">rmarkdown</span></a> in <a href="https://posit.co/download/rstudio-desktop/" target="_blank"><span class="fa fa-registered"></span> RStudio</a>. Currently using the free <a href="https://bootswatch.com/yeti/" target="_blank"><span style="font-family: monospace;">yeti</span> theme from Bootswatch</a>.</span></p>
</body>
</html>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
